import {
  type NegativeLabStockRegistryEntryV1,
  type NegativeLabStockRegistryV1,
  negativeLabStockRegistryAvailabilityV1Schema,
  negativeLabStockRegistryCategoryV1Schema,
  negativeLabStockRegistryClaimTierV1Schema,
  negativeLabStockRegistryEntryV1Schema,
  negativeLabStockRegistryFixtureStatusV1Schema,
  negativeLabStockRegistryIdV1Schema,
  negativeLabStockRegistryLegalNamingStatusV1Schema,
  negativeLabStockRegistryProcessFamilyV1Schema,
  negativeLabStockRegistryProfileStatusV1Schema,
  negativeLabStockRegistryV1Schema,
} from '../../../packages/rawengine-schema/src/rawEngineSchemas';

const NEGATIVE_LAB_STOCK_REGISTRY_SCHEMA_VERSION = 1;

const negativeLabStockRegistryProcessFamilySchema = negativeLabStockRegistryProcessFamilyV1Schema;
const negativeLabStockRegistryCategorySchema = negativeLabStockRegistryCategoryV1Schema;
const negativeLabStockRegistryAvailabilitySchema = negativeLabStockRegistryAvailabilityV1Schema;
const negativeLabStockRegistryClaimTierSchema = negativeLabStockRegistryClaimTierV1Schema;
const negativeLabStockRegistryLegalNamingStatusSchema = negativeLabStockRegistryLegalNamingStatusV1Schema;
const negativeLabStockRegistryFixtureStatusSchema = negativeLabStockRegistryFixtureStatusV1Schema;
const negativeLabStockRegistryProfileStatusSchema = negativeLabStockRegistryProfileStatusV1Schema;
export const negativeLabStockRegistryIdSchema = negativeLabStockRegistryIdV1Schema;
export const negativeLabStockRegistryEntrySchema = negativeLabStockRegistryEntryV1Schema;
export const negativeLabStockRegistrySchema = negativeLabStockRegistryV1Schema;

export type NegativeLabStockRegistry = NegativeLabStockRegistryV1;
type NegativeLabStockRegistryEntry = NegativeLabStockRegistryEntryV1;
type NegativeLabStockRegistryId = NegativeLabStockRegistryEntryV1['registryId'];

const parseNegativeLabStockRegistry = (value: unknown): NegativeLabStockRegistry =>
  negativeLabStockRegistrySchema.parse(value);
