import {
  type NegativeLabStockRegistryEntryV1,
  type NegativeLabStockRegistryV1,
  negativeLabStockRegistryAvailabilityV1Schema,
  negativeLabStockRegistryCategoryV1Schema,
  negativeLabStockRegistryClaimTierV1Schema,
  negativeLabStockRegistryEntryV1Schema,
  negativeLabStockRegistryFixtureStatusV1Schema,
  negativeLabStockRegistryIdV1Schema,
  negativeLabStockRegistryLegalNamingStatusV1Schema,
  negativeLabStockRegistryProcessFamilyV1Schema,
  negativeLabStockRegistryProfileStatusV1Schema,
  negativeLabStockRegistryV1Schema,
} from '../../../packages/rawengine-schema/src/rawEngineSchemas';

export const NEGATIVE_LAB_STOCK_REGISTRY_SCHEMA_VERSION = 1;

export const negativeLabStockRegistryProcessFamilySchema = negativeLabStockRegistryProcessFamilyV1Schema;
export const negativeLabStockRegistryCategorySchema = negativeLabStockRegistryCategoryV1Schema;
export const negativeLabStockRegistryAvailabilitySchema = negativeLabStockRegistryAvailabilityV1Schema;
export const negativeLabStockRegistryClaimTierSchema = negativeLabStockRegistryClaimTierV1Schema;
export const negativeLabStockRegistryLegalNamingStatusSchema = negativeLabStockRegistryLegalNamingStatusV1Schema;
export const negativeLabStockRegistryFixtureStatusSchema = negativeLabStockRegistryFixtureStatusV1Schema;
export const negativeLabStockRegistryProfileStatusSchema = negativeLabStockRegistryProfileStatusV1Schema;
export const negativeLabStockRegistryIdSchema = negativeLabStockRegistryIdV1Schema;
export const negativeLabStockRegistryEntrySchema = negativeLabStockRegistryEntryV1Schema;
export const negativeLabStockRegistrySchema = negativeLabStockRegistryV1Schema;

export type NegativeLabStockRegistry = NegativeLabStockRegistryV1;
export type NegativeLabStockRegistryEntry = NegativeLabStockRegistryEntryV1;
export type NegativeLabStockRegistryId = NegativeLabStockRegistryEntryV1['registryId'];

export const parseNegativeLabStockRegistry = (value: unknown): NegativeLabStockRegistry =>
  negativeLabStockRegistrySchema.parse(value);
