// @generated by src-tauri/render-abi/render-abi.toml; do not edit by hand.
// Keep semantic processing code in gpu_processing.rs.
#[allow(dead_code)]
pub(super) const RENDER_ABI_SCHEMA_VERSION: u32 = 1;
#[allow(dead_code)]
pub(super) const RENDER_ABI_LAYOUT_VERSION: u32 = 2;
#[allow(dead_code)]
pub(super) const MAX_MASK_BINDINGS: u32 = 1;

pub(super) const MAIN_BINDING_INPUT_TEXTURE: u32 = 0;
pub(super) const MAIN_BINDING_OUTPUT_TEXTURE: u32 = 1;
pub(super) const MAIN_BINDING_ADJUSTMENTS: u32 = 2;
pub(super) const MAIN_BINDING_MASK_TEXTURES: u32 = 3;
pub(super) const MAIN_BINDING_LUT_TEXTURE: u32 = 4;
pub(super) const MAIN_BINDING_LUT_SAMPLER: u32 = 5;
pub(super) const MAIN_BINDING_SHARPNESS_BLUR: u32 = 6;
pub(super) const MAIN_BINDING_TONAL_BLUR: u32 = 7;
pub(super) const MAIN_BINDING_CLARITY_BLUR: u32 = 8;
pub(super) const MAIN_BINDING_STRUCTURE_BLUR: u32 = 9;
pub(super) const MAIN_BINDING_DEHAZE_BLUR: u32 = 10;
pub(super) const MAIN_BINDING_FLARE_TEXTURE: u32 = 11;
pub(super) const MAIN_BINDING_FLARE_SAMPLER: u32 = 12;
