// @generated by src-tauri/render-abi/render-abi.toml; do not edit by hand.
// Keep semantic processing code in gpu_processing.rs.
#[allow(dead_code)]
pub(super) const RENDER_ABI_SCHEMA_VERSION: u32 = 1;
#[allow(dead_code)]
pub(super) const RENDER_ABI_LAYOUT_VERSION: u32 = 2;
#[allow(dead_code)]
pub(super) const MAX_MASK_BINDINGS: u32 = 1;

pub(super) const MAIN_BINDING_INPUT_TEXTURE: u32 = 0;
pub(super) const MAIN_BINDING_OUTPUT_TEXTURE: u32 = 1;
pub(super) const MAIN_BINDING_ADJUSTMENTS: u32 = 2;
pub(super) const MAIN_BINDING_MASK_TEXTURES: u32 = 3;
pub(super) const MAIN_BINDING_LUT_TEXTURE: u32 = 4;
pub(super) const MAIN_BINDING_LUT_SAMPLER: u32 = 5;
pub(super) const MAIN_BINDING_SHARPNESS_BLUR: u32 = 6;
pub(super) const MAIN_BINDING_TONAL_BLUR: u32 = 7;
pub(super) const MAIN_BINDING_CLARITY_BLUR: u32 = 8;
pub(super) const MAIN_BINDING_STRUCTURE_BLUR: u32 = 9;
pub(super) const MAIN_BINDING_DEHAZE_BLUR: u32 = 10;
pub(super) const MAIN_BINDING_FLARE_TEXTURE: u32 = 11;
pub(super) const MAIN_BINDING_FLARE_SAMPLER: u32 = 12;

#[allow(dead_code)]
pub(super) const RENDER_ABI_ALL_ADJUSTMENTS_FIELDS: &[&str] = &["global", "mask_adjustments", "mask_count", "tile_offset_x", "tile_offset_y", "mask_atlas_cols", "blur_pass_flags", "execution_phase", "source_width", "source_height"];
#[allow(dead_code)]
pub(super) const RENDER_ABI_GLOBAL_ADJUSTMENTS_FIELDS: &[&str] = &["exposure", "brightness", "contrast", "highlights", "shadows", "whites", "blacks", "saturation", "temperature", "tint", "vibrance", "hue", "edit_graph_version", "dehaze_atmosphere_r", "dehaze_atmosphere_g", "dehaze_atmosphere_b", "technical_white_balance", "sharpness", "luma_noise_reduction", "color_noise_reduction", "clarity", "dehaze", "structure", "centre", "vignette_amount", "vignette_midpoint", "vignette_roundness", "vignette_feather", "grain_amount", "grain_size", "grain_roughness", "chromatic_aberration_red_cyan", "chromatic_aberration_blue_yellow", "show_clipping", "is_raw_image", "dehaze_atmosphere_confidence", "has_lut", "lut_intensity", "tonemapper_mode", "_pad_lut2", "_pad_lut3", "_pad_lut4", "_pad_lut5", "_pad_agx1", "_pad_agx2", "_pad_agx3", "_pad_wgsl_agx_align1", "_pad_wgsl_agx_align2", "_pad_wgsl_agx_align3", "agx_pipe_to_rendering_matrix", "agx_rendering_to_pipe_matrix", "rapid_view_parameters0", "rapid_view_parameters1", "rapid_view_parameters2", "_pad_cg1", "_pad_cg2", "_pad_cg3", "_pad_cg4", "color_grading_shadows", "color_grading_midtones", "color_grading_highlights", "color_grading_global", "color_grading_blending", "color_grading_balance", "_pad2", "_pad3", "color_calibration", "color_balance_rgb", "channel_mixer", "black_white_mixer", "levels", "hsl", "luma_curve", "red_curve", "green_curve", "blue_curve", "luma_curve_count", "red_curve_count", "green_curve_count", "blue_curve_count", "_pad_end1", "_pad_end2", "_pad_end3", "_pad_end4", "glow_amount", "halation_amount", "flare_amount", "sharpness_threshold", "tone_equalizer", "point_color", "perceptual_grading", "scene_curve_knots", "scene_curve_parameters", "output_curve_knots", "output_curve_parameters"];
#[allow(dead_code)]
pub(super) const RENDER_ABI_MASK_ADJUSTMENTS_FIELDS: &[&str] = &["exposure", "brightness", "contrast", "highlights", "shadows", "whites", "blacks", "saturation", "temperature", "tint", "vibrance", "sharpness", "luma_noise_reduction", "color_noise_reduction", "clarity", "dehaze", "structure", "glow_amount", "halation_amount", "flare_amount", "sharpness_threshold", "hue", "blend_mode", "_pad_cg2", "color_grading_shadows", "color_grading_midtones", "color_grading_highlights", "color_grading_global", "color_grading_blending", "color_grading_balance", "_pad5", "_pad6", "hsl", "luma_curve", "red_curve", "green_curve", "blue_curve", "luma_curve_count", "red_curve_count", "green_curve_count", "blue_curve_count", "_pad_end4", "_pad_end5", "_pad_end6", "_pad_end7", "tone_equalizer", "point_color", "perceptual_grading"];
