pub(crate) struct AdjustmentScales {
    pub(crate) exposure: f32,
    pub(crate) brightness: f32,
    pub(crate) contrast: f32,
    pub(crate) highlights: f32,
    pub(crate) shadows: f32,
    pub(crate) whites: f32,
    pub(crate) blacks: f32,
    pub(crate) saturation: f32,
    pub(crate) temperature: f32,
    pub(crate) tint: f32,
    pub(crate) vibrance: f32,
    pub(crate) sharpness: f32,
    pub(crate) sharpness_threshold: f32,
    pub(crate) luma_noise_reduction: f32,
    pub(crate) color_noise_reduction: f32,
    pub(crate) clarity: f32,
    pub(crate) dehaze: f32,
    pub(crate) structure: f32,
    pub(crate) centré: f32,
    pub(crate) vignette_amount: f32,
    pub(crate) vignette_midpoint: f32,
    pub(crate) vignette_roundness: f32,
    pub(crate) vignette_feather: f32,
    pub(crate) grain_amount: f32,
    pub(crate) grain_size: f32,
    pub(crate) grain_roughness: f32,
    pub(crate) chromatic_aberration: f32,
    pub(crate) hsl_hue_multiplier: f32,
    pub(crate) hsl_saturation: f32,
    pub(crate) hsl_luminance: f32,
    pub(crate) color_grading_saturation: f32,
    pub(crate) color_grading_luminance: f32,
    pub(crate) color_grading_blending: f32,
    pub(crate) color_grading_balance: f32,
    pub(crate) color_calibration_hue: f32,
    pub(crate) color_calibration_saturation: f32,
    pub(crate) glow: f32,
    pub(crate) halation: f32,
    pub(crate) flares: f32,
}

pub(crate) const SCALES: AdjustmentScales = AdjustmentScales {
    exposure: 0.8,
    brightness: 0.8,
    contrast: 100.0,
    highlights: 120.0,
    shadows: 120.0,
    whites: 30.0,
    blacks: 70.0,
    saturation: 100.0,
    temperature: 25.0,
    tint: 100.0,
    vibrance: 100.0,
    sharpness: 50.0,
    sharpness_threshold: 100.0,
    luma_noise_reduction: 100.0,
    color_noise_reduction: 100.0,
    clarity: 200.0,
    dehaze: 750.0,
    structure: 200.0,
    centré: 250.0,
    vignette_amount: 100.0,
    vignette_midpoint: 100.0,
    vignette_roundness: 100.0,
    vignette_feather: 100.0,
    grain_amount: 200.0,
    grain_size: 50.0,
    grain_roughness: 100.0,
    chromatic_aberration: 10000.0,
    hsl_hue_multiplier: 0.3,
    hsl_saturation: 100.0,
    hsl_luminance: 100.0,
    color_grading_saturation: 500.0,
    color_grading_luminance: 500.0,
    color_grading_blending: 100.0,
    color_grading_balance: 200.0,
    color_calibration_hue: 400.0,
    color_calibration_saturation: 120.0,
    glow: 100.0,
    halation: 100.0,
    flares: 100.0,
};
