use super::{CalibrationFitReceipt, IlluminantCoordinates};
use anyhow::{Result, anyhow, ensure};
use nalgebra::Matrix3;

const TAG_UNIQUE_CAMERA_MODEL: u16 = 50_708;
const TAG_COLOR_MATRIX_1: u16 = 50_721;
const TAG_COLOR_MATRIX_2: u16 = 50_722;
const TAG_CALIBRATION_ILLUMINANT_1: u16 = 50_778;
const TAG_CALIBRATION_ILLUMINANT_2: u16 = 50_779;
const TAG_PROFILE_CALIBRATION_SIGNATURE: u16 = 50_932;
const TAG_PROFILE_NAME: u16 = 50_936;
const TAG_EMBED_POLICY: u16 = 50_941;
const TAG_PROFILE_COPYRIGHT: u16 = 50_942;

pub(crate) fn encode_generated_matrix_dcp(
    receipt: &CalibrationFitReceipt,
    profile_name: &str,
) -> Result<Vec<u8>> {
    ensure!(
        receipt.quality_status.publishable(),
        "chart_calibration_profile_not_publishable"
    );
    let name = bounded_ascii(profile_name, 96, "chart_calibration_profile_name_invalid")?;
    let camera = bounded_ascii(
        &receipt.camera_identity,
        96,
        "chart_calibration_camera_identity_invalid",
    )?;
    let camera_to_xyz = Matrix3::from_row_slice(&receipt.camera_to_xyz.concat());
    let xyz_to_camera = camera_to_xyz
        .try_inverse()
        .ok_or_else(|| anyhow!("chart_calibration_profile_matrix_singular"))?;
    ensure!(
        xyz_to_camera.iter().all(|value| value.is_finite()),
        "chart_calibration_profile_matrix_invalid"
    );
    let matrix = (0..3)
        .flat_map(|row| {
            (0..3).flat_map(move |column| signed_rational(xyz_to_camera[(row, column)], 1_000_000))
        })
        .collect::<Vec<_>>();
    let illuminant = calibration_illuminant_code(receipt.illuminant)
        .to_le_bytes()
        .to_vec();
    let fields = vec![
        (TAG_UNIQUE_CAMERA_MODEL, 2, nul_terminated(camera)),
        (TAG_COLOR_MATRIX_1, 10, matrix),
        (TAG_CALIBRATION_ILLUMINANT_1, 3, illuminant),
        (
            TAG_PROFILE_CALIBRATION_SIGNATURE,
            2,
            nul_terminated("RapidRaw generated calibration v1".into()),
        ),
        (TAG_PROFILE_NAME, 2, nul_terminated(name)),
        (TAG_EMBED_POLICY, 4, 0u32.to_le_bytes().to_vec()),
        (
            TAG_PROFILE_COPYRIGHT,
            2,
            nul_terminated(
                "Generated by RapidRaw from user-owned measurements; AGPL-3.0-or-later tooling"
                    .into(),
            ),
        ),
    ];
    encode_tiff(fields)
}

pub(crate) fn encode_generated_dual_matrix_dcp(
    warm: &CalibrationFitReceipt,
    cool: &CalibrationFitReceipt,
    profile_name: &str,
) -> Result<Vec<u8>> {
    ensure!(
        warm.quality_status.publishable() && cool.quality_status.publishable(),
        "chart_calibration_dual_endpoint_not_publishable"
    );
    ensure!(
        warm.camera_identity == cool.camera_identity
            && warm.chart_id == cool.chart_id
            && warm.chart_version == cool.chart_version
            && warm.raw_processing_profile == cool.raw_processing_profile,
        "chart_calibration_dual_endpoint_incompatible"
    );
    let warm_cct = warm.illuminant.cct_kelvin.unwrap_or(0.0);
    let cool_cct = cool.illuminant.cct_kelvin.unwrap_or(0.0);
    ensure!(
        warm_cct >= 1_500.0 && cool_cct - warm_cct >= 1_500.0,
        "chart_calibration_dual_illuminants_too_close"
    );
    let name = bounded_ascii(profile_name, 96, "chart_calibration_profile_name_invalid")?;
    let camera = bounded_ascii(
        &warm.camera_identity,
        96,
        "chart_calibration_camera_identity_invalid",
    )?;
    let fields = vec![
        (TAG_UNIQUE_CAMERA_MODEL, 2, nul_terminated(camera)),
        (TAG_COLOR_MATRIX_1, 10, encoded_xyz_to_camera(warm)?),
        (TAG_COLOR_MATRIX_2, 10, encoded_xyz_to_camera(cool)?),
        (
            TAG_CALIBRATION_ILLUMINANT_1,
            3,
            calibration_illuminant_code(warm.illuminant)
                .to_le_bytes()
                .to_vec(),
        ),
        (
            TAG_CALIBRATION_ILLUMINANT_2,
            3,
            calibration_illuminant_code(cool.illuminant)
                .to_le_bytes()
                .to_vec(),
        ),
        (
            TAG_PROFILE_CALIBRATION_SIGNATURE,
            2,
            nul_terminated("RapidRaw generated dual calibration v1".into()),
        ),
        (TAG_PROFILE_NAME, 2, nul_terminated(name)),
        (TAG_EMBED_POLICY, 4, 0u32.to_le_bytes().to_vec()),
        (
            TAG_PROFILE_COPYRIGHT,
            2,
            nul_terminated(
                "Generated by RapidRaw from user-owned measurements; AGPL-3.0-or-later tooling"
                    .into(),
            ),
        ),
    ];
    encode_tiff(fields)
}

fn encoded_xyz_to_camera(receipt: &CalibrationFitReceipt) -> Result<Vec<u8>> {
    let camera_to_xyz = Matrix3::from_row_slice(&receipt.camera_to_xyz.concat());
    let xyz_to_camera = camera_to_xyz
        .try_inverse()
        .ok_or_else(|| anyhow!("chart_calibration_profile_matrix_singular"))?;
    ensure!(
        xyz_to_camera.iter().all(|value| value.is_finite()),
        "chart_calibration_profile_matrix_invalid"
    );
    Ok((0..3)
        .flat_map(|row| {
            (0..3).flat_map(move |column| signed_rational(xyz_to_camera[(row, column)], 1_000_000))
        })
        .collect())
}

fn calibration_illuminant_code(illuminant: IlluminantCoordinates) -> u16 {
    let cct = illuminant.cct_kelvin.unwrap_or(6504.0);
    if cct < 3500.0 {
        17 // Standard light A
    } else if cct < 5750.0 {
        23 // D50
    } else {
        21 // D65
    }
}

fn encode_tiff(mut fields: Vec<(u16, u16, Vec<u8>)>) -> Result<Vec<u8>> {
    fields.sort_by_key(|field| field.0);
    let mut bytes = vec![b'I', b'I', 42, 0, 8, 0, 0, 0];
    bytes.extend_from_slice(
        &u16::try_from(fields.len())
            .map_err(|_| anyhow!("chart_calibration_profile_field_count_invalid"))?
            .to_le_bytes(),
    );
    let data_start = 8 + 2 + fields.len() * 12 + 4;
    let mut data = Vec::new();
    for (tag, kind, value) in fields {
        let width = match kind {
            2 => 1,
            3 => 2,
            4 => 4,
            10 => 8,
            _ => return Err(anyhow!("chart_calibration_profile_field_type_invalid")),
        };
        ensure!(
            value.len() % width == 0,
            "chart_calibration_profile_field_size_invalid"
        );
        bytes.extend_from_slice(&tag.to_le_bytes());
        bytes.extend_from_slice(&kind.to_le_bytes());
        bytes.extend_from_slice(
            &u32::try_from(value.len() / width)
                .map_err(|_| anyhow!("chart_calibration_profile_field_size_invalid"))?
                .to_le_bytes(),
        );
        if value.len() <= 4 {
            let mut inline = [0; 4];
            inline[..value.len()].copy_from_slice(&value);
            bytes.extend_from_slice(&inline);
        } else {
            bytes.extend_from_slice(
                &u32::try_from(data_start + data.len())
                    .map_err(|_| anyhow!("chart_calibration_profile_offset_invalid"))?
                    .to_le_bytes(),
            );
            data.extend_from_slice(&value);
        }
    }
    bytes.extend_from_slice(&0u32.to_le_bytes());
    bytes.extend_from_slice(&data);
    Ok(bytes)
}

fn signed_rational(value: f64, denominator: i32) -> [u8; 8] {
    let numerator = (value * f64::from(denominator))
        .round()
        .clamp(f64::from(i32::MIN), f64::from(i32::MAX)) as i32;
    let mut bytes = [0; 8];
    bytes[..4].copy_from_slice(&numerator.to_le_bytes());
    bytes[4..].copy_from_slice(&denominator.to_le_bytes());
    bytes
}

fn bounded_ascii(value: &str, maximum: usize, error: &'static str) -> Result<String> {
    let trimmed = value.trim();
    ensure!(!trimmed.is_empty() && trimmed.len() <= maximum, error);
    ensure!(
        trimmed
            .bytes()
            .all(|byte| byte.is_ascii_graphic() || byte == b' '),
        error
    );
    Ok(trimmed.to_string())
}

fn nul_terminated(mut value: String) -> Vec<u8> {
    value.push('\0');
    value.into_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::color::{
        calibration::{
            CALIBRATION_CONTRACT, CALIBRATION_SOLVER_VERSION, CalibrationQualityStatus,
            ColorErrorMetrics,
        },
        camera_profile::{DcpParseLimits, parse_dcp},
    };

    #[test]
    fn generated_matrix_profile_roundtrips_through_strict_dcp_parser() {
        let metrics = ColorErrorMetrics {
            mean_delta_e00: 0.2,
            median_delta_e00: 0.2,
            p95_delta_e00: 0.4,
            max_delta_e00: 0.5,
            neutral_axis_error: 0.1,
            skin_mean_delta_e00: Some(0.2),
        };
        let receipt = CalibrationFitReceipt {
            contract: CALIBRATION_CONTRACT.into(),
            implementation_version: CALIBRATION_SOLVER_VERSION,
            camera_identity: "Synthetic Camera".into(),
            source_revision: "revision".into(),
            raw_processing_profile: "technical".into(),
            chart_id: "chart".into(),
            chart_version: 1,
            chart_reference_illuminant: "D65".into(),
            chart_observer: "CIE 1931 2 degree".into(),
            chart_provenance: "test".into(),
            chart_license: "CC0-1.0".into(),
            chart_source_url: "https://example.invalid/chart".into(),
            illuminant: IlluminantCoordinates {
                x: 0.3127,
                y: 0.3290,
                cct_kelvin: Some(6504.0),
                duv: Some(0.0),
            },
            adaptation: "Bradford".into(),
            train_patch_ids: vec!["a".into()],
            validation_patch_ids: vec!["b".into()],
            camera_to_xyz: [[0.7, 0.2, 0.1], [0.1, 0.8, 0.1], [0.02, 0.08, 0.9]],
            condition_number: 1.5,
            rejected_patch_ids: Vec::new(),
            train_metrics: metrics.clone(),
            validation_metrics: metrics,
            residual_model_accepted: false,
            quality_status: CalibrationQualityStatus::Excellent,
            warning_codes: Vec::new(),
            solver_fingerprint: "blake3:test".into(),
        };
        let bytes = encode_generated_matrix_dcp(&receipt, "Studio D65").unwrap();
        let profile = parse_dcp(&bytes, DcpParseLimits::default()).unwrap();
        assert_eq!(profile.name, "Studio D65");
        assert_eq!(profile.camera_model.as_deref(), Some("Synthetic Camera"));
        assert_eq!(profile.calibration_illuminants[0], Some(21));
        assert!(profile.color_matrices[0].is_some());

        let mut warm = receipt.clone();
        warm.illuminant = IlluminantCoordinates {
            x: 0.44757,
            y: 0.40745,
            cct_kelvin: Some(2856.0),
            duv: Some(0.0),
        };
        warm.camera_to_xyz[0][0] += 0.02;
        let dual = encode_generated_dual_matrix_dcp(&warm, &receipt, "Studio A + D65").unwrap();
        let dual_profile = parse_dcp(&dual, DcpParseLimits::default()).unwrap();
        assert_eq!(dual_profile.calibration_illuminants, [Some(17), Some(21)]);
        assert!(dual_profile.color_matrices.iter().all(Option::is_some));
    }
}
