export const VISUAL_SMOKE_SCENARIO_IDS = {
  AdjustmentsPanelRetune: 'adjustments-panel-retune',
  AgentChatUi: 'agent-chat-ui',
  AgentSelectedImageLiveSession: 'agent-selected-image-live-session',
  BrushMaskCanvasUi: 'brush-mask-canvas-ui',
  ColorAdjustmentDensity: 'color-adjustment-density',
  ColorWorkflow: 'color-workflow',
  ColorRangeLocalAdjustment: 'color-range-local-adjustment',
  ColorWheelInstances: 'color-wheel-instances',
  CommandPaletteWorkflows: 'command-palette-workflows',
  CullingCompareSync: 'culling-compare-sync',
  DetailDustSpot: 'detail-dust-spot',
  DetailWorkspace: 'detail-workspace',
  EditorParityContract: 'editor-parity-contract',
  EmptyLibrary: 'empty-library',
  FilmLookBrowser: 'film-look-browser',
  FocusPrivateRawModalReview: 'focus-private-raw-modal-review',
  FocusPrivateRawUi: 'focus-private-raw-ui',
  FocusUi: 'focus-ui',
  HdrPrivateRawEditorHandoff: 'hdr-private-raw-editor-handoff',
  HdrPrivateRawUi: 'hdr-private-raw-ui',
  HdrSavedOutputEditorPath: 'hdr-saved-output-editor-path',
  HdrUi: 'hdr-ui',
  LayerBrushLocalAdjustment: 'layer-brush-local-adjustment',
  LayerMaskPrivateRawUi: 'layer-mask-private-raw-ui',
  LayerStackWorkflow: 'layer-stack-workflow',
  LensCorrectionSession: 'lens-correction-session',
  NavigatorPreviewArtifact: 'navigator-preview-artifact',
  TransformPreviewSession: 'transform-preview-session',
  LibraryWorkflow: 'library-workflow',
  MaskOverlayRawProof: 'mask-overlay-raw-proof',
  NegativeLabBatchColorWorkspace: 'negative-lab-batch-color-workspace',
  NegativeLabEditorLayerHandoff: 'negative-lab-editor-layer-handoff',
  NegativeLabPublicExportReview: 'negative-lab-public-export-review',
  NegativeLabRealRawPrivateReview: 'negative-lab-real-raw-private-review',
  NegativeLabWorkspace: 'negative-lab-workspace',
  ObjectPromptUi: 'object-prompt-ui',
  ComputationalPanoramaOutputReview: 'computational-panorama-output-review',
  PanoramaPrivateRawUi: 'panorama-private-raw-ui',
  PanoramaProcessingCommand: 'panorama-processing-command',
  PanoramaSavedReview: 'panorama-saved-review',
  PanoramaUi: 'panorama-ui',
  ProfessionalAdjustmentsCompact: 'professional-adjustments-compact',
  ProfessionalEditorCompactPortrait: 'professional-editor-compact-portrait',
  ProfessionalEditorStatusChips: 'professional-editor-status-chips',
  ProfessionalCanvasOverlays: 'professional-canvas-overlays',
  ProfessionalCropTransformWorkspace: 'professional-crop-transform-workspace',
  ProfessionalFilmstripContext: 'professional-filmstrip-context',
  ProfessionalLayersCompact: 'professional-layers-compact',
  ProfessionalExportProofFooter: 'professional-export-proof-footer',
  ProfessionalEditorShell: 'professional-editor-shell',
  ProfessionalEditorToolbar: 'professional-editor-toolbar',
  ProfessionalEditorTokens: 'professional-editor-tokens',
  ProfessionalAgentReview: 'professional-agent-review',
  ProfessionalAgentReviewWorkspace: 'professional-agent-review-workspace',
  SrPrivateRawModalReview: 'sr-private-raw-modal-review',
  SrPrivateRawUi: 'sr-private-raw-ui',
  SrUi: 'sr-ui',
  TetherDiscoveryUi: 'tether-discovery-ui',
  WorkflowRail: 'workflow-rail',
} as const;

export const VISUAL_SMOKE_PROOF_TEST_IDS = {
  CommandPaletteOpen: 'command-palette-open',
  CommandPaletteSelectSource: 'command-palette-select-source',
  CommandPaletteWorkflowProof: 'command-palette-workflow-proof',
  NegativeLabAcceptBatchPlan: 'negative-lab-accept-batch-plan',
  NegativeLabAgentActivity: 'negative-lab-agent-activity',
  NegativeLabAgentCommandSource: 'negative-lab-agent-command-source',
  NegativeLabAgentCommitState: 'negative-lab-agent-commit-state',
  NegativeLabAgentDryRunState: 'negative-lab-agent-dry-run-state',
  NegativeLabBatchReadiness: 'negative-lab-batch-readiness',
  NegativeLabExportJpegProof: 'negative-lab-export-jpeg-proof',
  NegativeLabEditorLayerHandoffProof: 'negative-lab-editor-layer-handoff-proof',
  NegativeLabQueuedCount: 'negative-lab-queued-count',
  NegativeLabSavedPathProof: 'negative-lab-saved-path-proof',
  NegativeLabWorkflowRail: 'negative-lab-workflow-rail',
  NegativeLabWorkspace: 'negative-lab-workspace',
  NegativeLabWorkspaceProof: 'negative-lab-workspace-proof',
} as const;

export const VISUAL_SMOKE_SCENARIOS = [
  {
    marker: 'Adjustments',
    mode: VISUAL_SMOKE_SCENARIO_IDS.AdjustmentsPanelRetune,
    compactOutputFile: 'adjustments-panel-retune-compact.png',
    outputFile: 'adjustments-panel-retune.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Adjustments',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalAdjustmentsCompact,
    outputFile: 'professional-adjustments-compact.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Editor Preview',
    mode: VISUAL_SMOKE_SCENARIO_IDS.EmptyLibrary,
    outputFile: 'empty-library.png',
    sectionMinimum: 4,
  },
  {
    marker: 'Command Palette Workflows',
    mode: VISUAL_SMOKE_SCENARIO_IDS.CommandPaletteWorkflows,
    outputFile: 'command-palette-workflows.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Culling compare sync',
    mode: VISUAL_SMOKE_SCENARIO_IDS.CullingCompareSync,
    outputFile: 'culling-compare-sync.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Lens correction session',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LensCorrectionSession,
    outputFile: 'lens-correction-session.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Navigator preview artifact',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NavigatorPreviewArtifact,
    outputFile: 'navigator-preview-artifact.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Transform preview session',
    mode: VISUAL_SMOKE_SCENARIO_IDS.TransformPreviewSession,
    outputFile: 'transform-preview-session.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Color wheel instances',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ColorWheelInstances,
    outputFile: 'color-wheel-instances.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Tethered camera discovery',
    mode: VISUAL_SMOKE_SCENARIO_IDS.TetherDiscoveryUi,
    outputFile: 'tether-discovery-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Agent chat UI smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.AgentChatUi,
    outputFile: 'agent-chat-ui.png',
    sectionMinimum: 1,
  },
  {
    appMode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalAgentReviewWorkspace,
    marker: 'Professional agent review workspace',
    mode: VISUAL_SMOKE_SCENARIO_IDS.AgentSelectedImageLiveSession,
    outputFile: 'agent-selected-image-live-session.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Professional agent review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalAgentReview,
    outputFile: 'professional-agent-review.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Professional agent review workspace',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalAgentReviewWorkspace,
    outputFile: 'professional-agent-review-workspace.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Brush mask canvas UI',
    mode: VISUAL_SMOKE_SCENARIO_IDS.BrushMaskCanvasUi,
    outputFile: 'brush-mask-canvas-ui.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Panorama review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaUi,
    outputFile: 'panorama-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Panorama saved review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaSavedReview,
    outputFile: 'panorama-saved-review.png',
    sectionMinimum: 1,
  },
  {
    appMode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaSavedReview,
    marker: 'Panorama saved review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ComputationalPanoramaOutputReview,
    outputFile: 'computational-panorama-output-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW panorama review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaPrivateRawUi,
    outputFile: 'panorama-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Panorama dry-run command',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaProcessingCommand,
    outputFile: 'panorama-processing-command.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Focus Stack Smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FocusUi,
    outputFile: 'focus-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW focus review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FocusPrivateRawUi,
    outputFile: 'focus-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW focus modal review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FocusPrivateRawModalReview,
    outputFile: 'focus-private-raw-modal-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'HDR merge setup',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrUi,
    outputFile: 'hdr-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'HDR saved output editor path',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrSavedOutputEditorPath,
    outputFile: 'hdr-saved-output-editor-path.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW HDR review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrPrivateRawUi,
    outputFile: 'hdr-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW HDR editor handoff',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrPrivateRawEditorHandoff,
    outputFile: 'hdr-private-raw-editor-handoff.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Super Resolution Smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.SrUi,
    outputFile: 'sr-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW SR review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.SrPrivateRawUi,
    outputFile: 'sr-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW SR review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.SrPrivateRawModalReview,
    outputFile: 'sr-private-raw-modal-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Negative Conversion',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabWorkspace,
    outputFile: 'negative-lab-workspace.png',
    sectionMinimum: 1,
  },
  {
    appMode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabWorkspace,
    marker: 'Negative Conversion',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabBatchColorWorkspace,
    outputFile: 'negative-lab-batch-color-workspace.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Negative Lab editor handoff',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabEditorLayerHandoff,
    outputFile: 'negative-lab-editor-layer-handoff.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Public negative export review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabPublicExportReview,
    outputFile: 'negative-lab-public-export-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW positive proof',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabRealRawPrivateReview,
    outputFile: 'negative-lab-real-raw-private-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Film Looks',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FilmLookBrowser,
    outputFile: 'film-look-browser.png',
    sectionMinimum: 2,
  },
  {
    compactOutputFile: 'professional-color-compact.png',
    marker: 'Color Workflow',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ColorWorkflow,
    outputFile: 'color-workflow.png',
    sectionMinimum: 2,
  },
  {
    appMode: VISUAL_SMOKE_SCENARIO_IDS.ColorWorkflow,
    compactOutputFile: 'color-adjustment-density-compact.png',
    marker: 'Color Workflow',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ColorAdjustmentDensity,
    outputFile: 'color-adjustment-density.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Color Range Local Adjustment',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ColorRangeLocalAdjustment,
    outputFile: 'color-range-local-adjustment.png',
    sectionMinimum: 2,
  },
  {
    compactOutputFile: 'editor-parity-contract-coarse-390x844.png',
    highDpiDeviceScaleFactor: 2,
    highDpiOutputFile: 'editor-parity-contract-1440x900-2x.png',
    marker: 'Editor parity contract',
    mode: VISUAL_SMOKE_SCENARIO_IDS.EditorParityContract,
    outputFile: 'editor-parity-contract-1440x900.png',
    reducedMotionOutputFile: 'editor-parity-contract-reduced-motion-1440x900.png',
    reviewOutputFile: 'editor-parity-contract-1224x768.png',
    reviewViewport: { height: 768, width: 1224 },
    sectionMinimum: 5,
    viewport: { height: 900, width: 1440 },
  },
  {
    marker: 'Workflow rail density',
    mode: VISUAL_SMOKE_SCENARIO_IDS.WorkflowRail,
    outputFile: 'workflow-rail.png',
    sectionMinimum: 2,
  },
  {
    compactOutputFile: 'professional-editor-tokens-compact.png',
    marker: 'Professional editor tokens',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalEditorTokens,
    outputFile: 'professional-editor-tokens-desktop.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Professional editor shell',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalEditorShell,
    outputFile: 'professional-editor-shell.png',
    sectionMinimum: 5,
  },
  {
    compactOutputFile: 'professional-editor-toolbar-compact.png',
    marker: 'Professional editor toolbar',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalEditorToolbar,
    outputFile: 'professional-editor-toolbar.png',
    sectionMinimum: 4,
  },
  {
    compactOutputFile: 'professional-export-proof-footer-compact.png',
    marker: 'Export proof footer',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalExportProofFooter,
    outputFile: 'professional-export-proof-footer.png',
    sectionMinimum: 5,
  },
  {
    compactOutputFile: 'professional-editor-compact-portrait-390.png',
    marker: 'Professional editor compact portrait',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalEditorCompactPortrait,
    outputFile: 'professional-editor-compact-portrait.png',
    sectionMinimum: 5,
  },
  {
    marker: 'Editor chrome status chips',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalEditorStatusChips,
    outputFile: 'professional-editor-status-chips.png',
    sectionMinimum: 2,
  },
  {
    compactOutputFile: 'professional-filmstrip-context-compact.png',
    marker: 'Professional filmstrip context',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalFilmstripContext,
    outputFile: 'professional-filmstrip-context.png',
    sectionMinimum: 4,
  },
  {
    compactOutputFile: 'professional-crop-transform-workspace-compact.png',
    marker: 'Professional crop transform workspace',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalCropTransformWorkspace,
    outputFile: 'professional-crop-transform-workspace.png',
    sectionMinimum: 3,
  },
  {
    compactOutputFile: 'professional-canvas-overlays-compact.png',
    marker: 'Professional canvas overlays',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalCanvasOverlays,
    outputFile: 'professional-canvas-overlays.png',
    sectionMinimum: 3,
  },
  {
    compactOutputFile: 'professional-layers-compact-portrait.png',
    marker: 'Professional layers compact',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ProfessionalLayersCompact,
    outputFile: 'professional-layers-compact.png',
    sectionMinimum: 4,
  },
  {
    marker: 'Local Adjustment Stack',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LayerStackWorkflow,
    outputFile: 'layer-stack-workflow.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Brush Local Adjustment',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LayerBrushLocalAdjustment,
    outputFile: 'layer-brush-local-adjustment.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Private RAW layer mask review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LayerMaskPrivateRawUi,
    outputFile: 'layer-mask-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Object prompt visual proof',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ObjectPromptUi,
    outputFile: 'object-prompt-ui.png',
    sectionMinimum: 2,
  },
  {
    marker: 'RAW Mask Overlay Review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.MaskOverlayRawProof,
    outputFile: 'mask-overlay-raw-proof.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Cull Session',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LibraryWorkflow,
    outputFile: 'library-workflow.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Zoom detail workspace',
    mode: VISUAL_SMOKE_SCENARIO_IDS.DetailWorkspace,
    outputFile: 'detail-workspace.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Overlay interaction proof',
    mode: VISUAL_SMOKE_SCENARIO_IDS.DetailDustSpot,
    outputFile: 'detail-dust-spot.png',
    sectionMinimum: 2,
  },
] as const;

export type VisualSmokeScenario = (typeof VISUAL_SMOKE_SCENARIOS)[number];
export type VisualSmokeMode = VisualSmokeScenario['mode'];

export const VISUAL_SMOKE_MODES = VISUAL_SMOKE_SCENARIOS.map((scenario) => scenario.mode);
