export const VISUAL_SMOKE_SCENARIO_IDS = {
  AgentChatUi: 'agent-chat-ui',
  BrushMaskCanvasUi: 'brush-mask-canvas-ui',
  ColorWorkflow: 'color-workflow',
  CommandPaletteWorkflows: 'command-palette-workflows',
  DetailDustSpot: 'detail-dust-spot',
  DetailWorkspace: 'detail-workspace',
  EmptyLibrary: 'empty-library',
  FilmLookBrowser: 'film-look-browser',
  FocusPrivateRawUi: 'focus-private-raw-ui',
  FocusUi: 'focus-ui',
  HdrPrivateRawUi: 'hdr-private-raw-ui',
  HdrSavedOutputEditorPath: 'hdr-saved-output-editor-path',
  HdrUi: 'hdr-ui',
  LayerMaskPrivateRawUi: 'layer-mask-private-raw-ui',
  LayerStackWorkflow: 'layer-stack-workflow',
  LibraryWorkflow: 'library-workflow',
  MaskOverlayRawProof: 'mask-overlay-raw-proof',
  NegativeLabBatchColorWorkspace: 'negative-lab-batch-color-workspace',
  NegativeLabPublicExportReview: 'negative-lab-public-export-review',
  NegativeLabRealRawPrivateReview: 'negative-lab-real-raw-private-review',
  NegativeLabWorkspace: 'negative-lab-workspace',
  PanoramaPrivateRawUi: 'panorama-private-raw-ui',
  PanoramaSavedReview: 'panorama-saved-review',
  PanoramaUi: 'panorama-ui',
  SrPrivateRawUi: 'sr-private-raw-ui',
  SrUi: 'sr-ui',
  WorkflowRail: 'workflow-rail',
} as const;

export const VISUAL_SMOKE_PROOF_TEST_IDS = {
  CommandPaletteOpen: 'command-palette-open',
  CommandPaletteWorkflowProof: 'command-palette-workflow-proof',
  NegativeLabAcceptBatchPlan: 'negative-lab-accept-batch-plan',
  NegativeLabAgentActivity: 'negative-lab-agent-activity',
  NegativeLabAgentCommandSource: 'negative-lab-agent-command-source',
  NegativeLabAgentCommitState: 'negative-lab-agent-commit-state',
  NegativeLabAgentDryRunState: 'negative-lab-agent-dry-run-state',
  NegativeLabBatchReadiness: 'negative-lab-batch-readiness',
  NegativeLabExportJpegProof: 'negative-lab-export-jpeg-proof',
  NegativeLabQueuedCount: 'negative-lab-queued-count',
  NegativeLabSavedPathProof: 'negative-lab-saved-path-proof',
  NegativeLabWorkflowRail: 'negative-lab-workflow-rail',
  NegativeLabWorkspace: 'negative-lab-workspace',
  NegativeLabWorkspaceProof: 'negative-lab-workspace-proof',
} as const;

export const VISUAL_SMOKE_SCENARIOS = [
  {
    marker: 'Editor Preview',
    mode: VISUAL_SMOKE_SCENARIO_IDS.EmptyLibrary,
    outputFile: 'empty-library.png',
    sectionMinimum: 4,
  },
  {
    marker: 'Command Palette Workflows',
    mode: VISUAL_SMOKE_SCENARIO_IDS.CommandPaletteWorkflows,
    outputFile: 'command-palette-workflows.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Agent chat UI smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.AgentChatUi,
    outputFile: 'agent-chat-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Brush mask canvas UI',
    mode: VISUAL_SMOKE_SCENARIO_IDS.BrushMaskCanvasUi,
    outputFile: 'brush-mask-canvas-ui.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Panorama review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaUi,
    outputFile: 'panorama-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Panorama saved review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaSavedReview,
    outputFile: 'panorama-saved-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW panorama review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.PanoramaPrivateRawUi,
    outputFile: 'panorama-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Focus Stack Smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FocusUi,
    outputFile: 'focus-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW focus review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FocusPrivateRawUi,
    outputFile: 'focus-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'HDR merge setup',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrUi,
    outputFile: 'hdr-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'HDR saved output editor path',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrSavedOutputEditorPath,
    outputFile: 'hdr-saved-output-editor-path.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW HDR review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.HdrPrivateRawUi,
    outputFile: 'hdr-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Super Resolution Smoke',
    mode: VISUAL_SMOKE_SCENARIO_IDS.SrUi,
    outputFile: 'sr-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW SR review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.SrPrivateRawUi,
    outputFile: 'sr-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Negative Conversion',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabWorkspace,
    outputFile: 'negative-lab-workspace.png',
    sectionMinimum: 1,
  },
  {
    appMode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabWorkspace,
    marker: 'Negative Conversion',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabBatchColorWorkspace,
    outputFile: 'negative-lab-batch-color-workspace.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Public negative export review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabPublicExportReview,
    outputFile: 'negative-lab-public-export-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Private RAW positive proof',
    mode: VISUAL_SMOKE_SCENARIO_IDS.NegativeLabRealRawPrivateReview,
    outputFile: 'negative-lab-real-raw-private-review.png',
    sectionMinimum: 1,
  },
  {
    marker: 'Film Looks',
    mode: VISUAL_SMOKE_SCENARIO_IDS.FilmLookBrowser,
    outputFile: 'film-look-browser.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Color Workflow',
    mode: VISUAL_SMOKE_SCENARIO_IDS.ColorWorkflow,
    outputFile: 'color-workflow.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Workflow rail density',
    mode: VISUAL_SMOKE_SCENARIO_IDS.WorkflowRail,
    outputFile: 'workflow-rail.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Local Adjustment Stack',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LayerStackWorkflow,
    outputFile: 'layer-stack-workflow.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Private RAW layer mask review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LayerMaskPrivateRawUi,
    outputFile: 'layer-mask-private-raw-ui.png',
    sectionMinimum: 1,
  },
  {
    marker: 'RAW Mask Overlay Review',
    mode: VISUAL_SMOKE_SCENARIO_IDS.MaskOverlayRawProof,
    outputFile: 'mask-overlay-raw-proof.png',
    sectionMinimum: 2,
  },
  {
    marker: 'Cull Session',
    mode: VISUAL_SMOKE_SCENARIO_IDS.LibraryWorkflow,
    outputFile: 'library-workflow.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Zoom detail workspace',
    mode: VISUAL_SMOKE_SCENARIO_IDS.DetailWorkspace,
    outputFile: 'detail-workspace.png',
    sectionMinimum: 3,
  },
  {
    marker: 'Overlay interaction proof',
    mode: VISUAL_SMOKE_SCENARIO_IDS.DetailDustSpot,
    outputFile: 'detail-dust-spot.png',
    sectionMinimum: 2,
  },
] as const;

export type VisualSmokeScenario = (typeof VISUAL_SMOKE_SCENARIOS)[number];
export type VisualSmokeMode = VisualSmokeScenario['mode'];

export const VISUAL_SMOKE_MODES = VISUAL_SMOKE_SCENARIOS.map((scenario) => scenario.mode);
