#!/usr/bin/env bun

import { readFileSync, writeFileSync } from 'node:fs';

export interface RenderAbiManifest {
  schemaVersion: number;
  layoutVersion: number;
  maxMaskBindings: number;
  bindings: Readonly<Record<string, number>>;
  structFields: Readonly<Record<string, readonly string[]>>;
  rustStructFields: Readonly<Record<string, readonly string[]>>;
}

const manifestPath = 'src-tauri/render-abi/render-abi.toml';
const rustOutputPath = 'src-tauri/src/gpu/generated_bindings.rs';
const wgslOutputPath = 'src-tauri/src/shaders/generated_bindings.wgsl';

const parseNumber = (text: string, key: string): number => {
  const match = text.match(new RegExp(`^${key}\\s*=\\s*(\\d+)\\s*$`, 'mu'));
  if (!match) throw new Error(`render ABI manifest is missing ${key}`);
  return Number(match[1]);
};

const parseBindings = (text: string): Record<string, number> => {
  const sectionStart = text.indexOf('[bindings.main]');
  const sectionTail = sectionStart >= 0 ? text.slice(sectionStart + '[bindings.main]'.length) : '';
  const section = sectionTail.split(/\r?\n\[/u, 1)[0];
  const bindings: Record<string, number> = {};
  for (const line of section.split(/\r?\n/u)) {
    const match = line.match(/^([a-z0-9_]+)\s*=\s*(\d+)\s*$/u);
    if (match) bindings[match[1]] = Number(match[2]);
  }
  if (Object.keys(bindings).length === 0) throw new Error('render ABI manifest has no main bindings');
  return bindings;
};

const parseFields = (text: string, sectionName: string): readonly string[] => {
  const sectionStart = text.indexOf(`[structs.${sectionName}]`);
  const sectionTail = sectionStart >= 0 ? text.slice(sectionStart + `[structs.${sectionName}]`.length) : '';
  const section = sectionTail.split(/\r?\n\[/u, 1)[0];
  const fields = section
    .match(/^fields\s*=\s*\[([^\]]+)\]\s*$/mu)?.[1]
    ?.split(',')
    .map((field) => field.trim().replace(/^"|"$/gu, ''))
    .filter(Boolean);
  if (!fields?.length) throw new Error(`render ABI manifest is missing ${sectionName} fields`);
  return fields;
};

const parseOptionalFields = (text: string, sectionName: string, key: string): readonly string[] | undefined => {
  const sectionStart = text.indexOf(`[structs.${sectionName}]`);
  const sectionTail = sectionStart >= 0 ? text.slice(sectionStart + `[structs.${sectionName}]`.length) : '';
  const section = sectionTail.split(/\r?\n\[/u, 1)[0];
  const fields = section
    .match(new RegExp(`^${key}\\s*=\\s*\\[([^\\]]+)\\]\\s*$`, 'mu'))?.[1]
    ?.split(',')
    .map((field) => field.trim().replace(/^"|"$/gu, ''))
    .filter(Boolean);
  return fields?.length ? fields : undefined;
};

export const parseManifest = (text: string): RenderAbiManifest => ({
  schemaVersion: parseNumber(text, 'schema_version'),
  layoutVersion: parseNumber(text, 'layout_version'),
  maxMaskBindings: parseNumber(text, 'max_mask_bindings'),
  bindings: parseBindings(text),
  structFields: {
    all_adjustments: parseFields(text, 'all_adjustments'),
    global_adjustments: parseFields(text, 'global_adjustments'),
    mask_adjustments: parseFields(text, 'mask_adjustments'),
  },
  rustStructFields: {
    all_adjustments:
      parseOptionalFields(text, 'all_adjustments', 'rust_fields') ?? parseFields(text, 'all_adjustments'),
    global_adjustments:
      parseOptionalFields(text, 'global_adjustments', 'rust_fields') ?? parseFields(text, 'global_adjustments'),
    mask_adjustments:
      parseOptionalFields(text, 'mask_adjustments', 'rust_fields') ?? parseFields(text, 'mask_adjustments'),
  },
});

const constantName = (name: string): string => name.toUpperCase();
const structConstantName = (name: string): string => name.toUpperCase();

const renderRustFieldMetadata = (manifest: RenderAbiManifest): string =>
  Object.entries(manifest.rustStructFields)
    .map(([name, fields]) => {
      const values = fields.map((field) => `"${field}"`).join(', ');
      return `#[allow(dead_code)]\npub(super) const RENDER_ABI_${structConstantName(name)}_FIELDS: &[&str] = &[${values}];`;
    })
    .join('\n');

const renderWgslFieldMetadata = (manifest: RenderAbiManifest): string =>
  Object.entries(manifest.structFields)
    .map(
      ([name, fields]) => `const RAPIDRAW_RENDER_ABI_${structConstantName(name)}_FIELD_COUNT: u32 = ${fields.length}u;`,
    )
    .join('\n');

export const renderRustBindings = (manifest: RenderAbiManifest): string => {
  const bindings = Object.entries(manifest.bindings)
    .map(([name, value]) => `pub(super) const MAIN_BINDING_${constantName(name)}: u32 = ${value};`)
    .join('\n');
  return `// @generated by ${manifestPath}; do not edit by hand.\n// Keep semantic processing code in gpu_processing.rs.\n#[allow(dead_code)]\npub(super) const RENDER_ABI_SCHEMA_VERSION: u32 = ${manifest.schemaVersion};\n#[allow(dead_code)]\npub(super) const RENDER_ABI_LAYOUT_VERSION: u32 = ${manifest.layoutVersion};\n#[allow(dead_code)]\npub(super) const MAX_MASK_BINDINGS: u32 = ${manifest.maxMaskBindings};\n\n${bindings}\n\n${renderRustFieldMetadata(manifest)}\n`;
};

export const renderWgslBindings = (manifest: RenderAbiManifest): string => {
  const bindings = Object.entries(manifest.bindings)
    .map(([name, value]) => `const MAIN_BINDING_${constantName(name)}: u32 = ${value}u;`)
    .join('\n');
  return `// @generated by ${manifestPath}; do not edit by hand.\nconst RAPIDRAW_RENDER_ABI_SCHEMA_VERSION: u32 = ${manifest.schemaVersion}u;\nconst RAPIDRAW_RENDER_ABI_LAYOUT_VERSION: u32 = ${manifest.layoutVersion}u;\n\n${bindings}\n\n${renderWgslFieldMetadata(manifest)}\n`;
};

const run = (mode: '--check' | '--write'): void => {
  const manifest = parseManifest(readFileSync(manifestPath, 'utf8'));
  const expected = [
    [rustOutputPath, renderRustBindings(manifest)],
    [wgslOutputPath, renderWgslBindings(manifest)],
  ] as const;
  const failures = expected.filter(([path, content]) => readFileSync(path, 'utf8') !== content).map(([path]) => path);
  if (mode === '--write') {
    for (const [path, content] of expected) writeFileSync(path, content);
    console.log(`Generated render ABI bindings (${Object.keys(manifest.bindings).length} bindings).`);
    return;
  }
  if (failures.length) throw new Error(`render ABI bindings are stale: ${failures.join(', ')}`);
  console.log(`Render ABI bindings are reproducible (${Object.keys(manifest.bindings).length} bindings).`);
};

if (import.meta.main) {
  const mode = process.argv[2];
  if (mode !== '--check' && mode !== '--write') throw new Error('usage: generate.ts --check|--write');
  run(mode);
}
