#!/usr/bin/env bun

import { readFileSync } from 'node:fs';

const locale = JSON.parse(readFileSync('src/i18n/locales/en.json', 'utf8'));
const cullingLocale = locale.modals?.culling;
const requiredLocaleKeys = [
  'batchPreview',
  'batchPreviewAlt',
  'batchPreviewMore_one',
  'batchPreviewMore_other',
  'compareFocus',
  'eyeSharpnessValue',
  'faceSharpnessValue',
  'focusConfidence',
  'focusConfidenceValue',
  'focusRankingsTab',
  'focusRankValue',
  'focusScore',
  'focusScoreValue',
  'compareLinked',
  'compareDimensions',
  'comparePanDown',
  'comparePanLeft',
  'comparePanReadout',
  'comparePanRight',
  'comparePanUp',
  'compareReset',
  'compareScore',
  'compareSharpness',
  'compareUnlinked',
  'compareViewport',
  'emptyAnalysisModes',
  'emptyBatch',
  'progressCount',
  'selectedResultCount_one',
  'selectedResultCount_other',
  'summaryAnalysisModeCount_one',
  'summaryAnalysisModeCount_other',
  'summaryAnalysisModes',
  'summaryBlur',
  'summaryDisabled',
  'summaryEnabled',
  'summaryEnabledThreshold',
  'summaryFocusRanking',
  'summarySimilar',
  'summarySourceCount_one',
  'summarySourceCount_other',
  'summarySourceMix',
  'summarySourceMixValue',
  'summarySources',
  'summaryWorkload',
  'summaryWorkloadValue_one',
  'summaryWorkloadValue_other',
];

const missingKeys = requiredLocaleKeys.filter((key) => typeof cullingLocale?.[key] !== 'string');
if (missingKeys.length > 0) {
  console.error(`Missing culling summary locale keys: ${missingKeys.join(', ')}`);
  process.exit(1);
}

const source = readFileSync('src/components/modals/CullingModal.tsx', 'utf8');
for (const marker of [
  'data-testid="culling-setup-summary"',
  'data-testid="culling-setup-batch-preview"',
  'data-preview-count={setupPreviewPaths.length}',
  'data-preview-overflow-count={setupPreviewOverflowCount}',
  'SETUP_PREVIEW_LIMIT = 6',
  'modals.culling.batchPreview',
  'modals.culling.batchPreviewMore',
  'data-testid="culling-empty-batch-guard"',
  'data-testid="culling-empty-analysis-mode-guard"',
  'settings.groupSimilar || settings.filterBlurry || settings.rankFocus',
  'Number(settings.groupSimilar) + Number(settings.filterBlurry) + Number(settings.rankFocus)',
  'const canStartCulling = imagePaths.length > 0 && hasCullingAnalysisMode',
  'disabled={!canStartCulling}',
  'modals.culling.emptyAnalysisModes',
  'modals.culling.emptyBatch',
  'data-testid="culling-progress-count"',
  'modals.culling.progressCount',
  'data-testid="culling-selected-result-count"',
  'modals.culling.selectedResultCount',
  'selectedRejects.size',
  'data-image-count={imagePaths.length}',
  'data-raw-source-count={sourceMix.raw}',
  'data-raster-source-count={sourceMix.raster}',
  'data-group-similar-enabled={String(settings.groupSimilar)}',
  'data-blur-filter-enabled={String(settings.filterBlurry)}',
  'data-focus-ranking-enabled={String(settings.rankFocus)}',
  'data-culling-analysis-mode-count={cullingAnalysisModeCount}',
  'data-testid="culling-focus-ranking-card"',
  'data-focus-eye-sharpness={img.eyeSharpnessMetric.toFixed(2)}',
  'data-focus-face-sharpness={img.faceSharpnessMetric.toFixed(2)}',
  'modals.culling.focusRankingsTab',
  'modals.culling.rankFocus',
  'modals.culling.rankFocusDesc',
  'modals.culling.eyeSharpnessValue',
  'modals.culling.faceSharpnessValue',
  'modals.culling.focusScoreValue',
  'modals.culling.focusConfidenceValue',
  'modals.culling.summaryAnalysisModes',
  'modals.culling.summaryAnalysisModeCount',
  'modals.culling.summarySourceMix',
  'modals.culling.summarySourceMixValue',
  'modals.culling.summaryWorkload',
  'modals.culling.summaryWorkloadValue',
  'data-testid="culling-compare-sync-controls"',
  'data-testid="culling-compare-link-toggle"',
  'data-testid={`culling-compare-zoom-${zoomPercent}`}',
  'data-testid="culling-compare-pan-up"',
  'data-testid="culling-compare-pan-left"',
  'data-testid="culling-compare-pan-right"',
  'data-testid="culling-compare-pan-down"',
  'data-testid="culling-compare-reset"',
  'data-viewport-linked={String(compareViewport.linked)}',
  'data-viewport-zoom={viewport.zoomPercent}',
  'data-center-focus={analysis.centerFocusMetric.toFixed(2)}',
  'data-sharpness={analysis.sharpnessMetric.toFixed(2)}',
  'modals.culling.compareViewport',
  'modals.culling.comparePanReadout',
  'compareViewport.linked',
  'nudgeCompareViewport',
]) {
  if (!source.includes(marker)) {
    console.error(`Culling setup summary missing marker: ${marker}`);
    process.exit(1);
  }
}

console.log('culling UI summary ok');
