#!/usr/bin/env bun

import { readFileSync } from 'node:fs';

const panelSource = readFileSync('src/components/panel/right/TetherPanel.tsx', 'utf8');
const editorViewSource = readFileSync('src/components/views/EditorView.tsx', 'utf8');
const schemaSource = readFileSync('src/schemas/tetheringSchemas.ts', 'utf8');
const registrySource = readFileSync('src/components/panel/right/rightPanelRegistry.ts', 'utf8');
const appPropertiesSource = readFileSync('src/components/ui/AppProperties.tsx', 'utf8');
const visualSmokeSource = readFileSync('src/validation/visual/VisualSmokeApp.tsx', 'utf8');
const visualSmokeScriptSource = readFileSync('scripts/capture-visual-smoke.ts', 'utf8');
const libSource = readFileSync('src-tauri/src/lib.rs', 'utf8');
const rustSource = readFileSync('src-tauri/src/tethering.rs', 'utf8');
const locale = JSON.parse(readFileSync('src/i18n/locales/en.json', 'utf8')) as {
  editor?: { tether?: Record<string, unknown> };
};

const requiredSnippets = [
  [panelSource, 'data-testid="tether-panel"'],
  [panelSource, 'data-testid="tether-camera-card"'],
  [panelSource, 'data-testid="tether-provider-status"'],
  [panelSource, 'data-testid="tether-session-status"'],
  [panelSource, 'data-testid="tether-session-destination-root"'],
  [panelSource, "t('editor.tether.sessionDestinationRoot'"],
  [panelSource, 'data-testid="tether-recovery-status"'],
  [panelSource, 'data-recovery-status={session.recovery.status}'],
  [panelSource, "t('editor.tether.recoveryQuarantined'"],
  [panelSource, 'data-testid="tether-open-session"'],
  [panelSource, 'data-testid="tether-close-session"'],
  [panelSource, 'data-testid="tether-trigger-capture"'],
  [panelSource, 'tetherDisabledControlClassName'],
  [panelSource, 'disabled:bg-bg-secondary disabled:text-text-tertiary disabled:ring-1 disabled:ring-border-color'],
  [panelSource, 'data-testid="tether-exposure-controls"'],
  [panelSource, 'data-testid={`tether-exposure-control-${control.id}`}'],
  [panelSource, 'setCameraControl({'],
  [panelSource, "t('editor.tether.controlVerified'"],
  [panelSource, 'data-testid="tether-capture-result"'],
  [panelSource, 'cameraControlValues: Object.fromEntries'],
  [panelSource, "t('editor.tether.controlsRecorded'"],
  [panelSource, 'data-testid="tether-incoming-capture-strip"'],
  [panelSource, 'data-testid="tether-review-mode-control"'],
  [panelSource, 'data-testid="tether-incoming-capture-item"'],
  [panelSource, "type TetherReviewMode = 'holdCurrent' | 'newest' | 'pinned'"],
  [panelSource, 'setCaptures((current) => [response, ...current].slice(0, 8))'],
  [panelSource, "reviewMode === 'newest'"],
  [panelSource, 'data-testid="tether-pin-capture"'],
  [panelSource, 'data-testid="tether-open-capture"'],
  [panelSource, 'data-testid="tether-open-selected-capture"'],
  [panelSource, 'data-testid="tether-ingest-preset-select"'],
  [panelSource, 'data-testid="tether-metadata-template-select"'],
  [panelSource, 'data-testid="tether-backup-copy-toggle"'],
  [panelSource, 'data-ingest-preset-id={capture.ingest.presetId}'],
  [panelSource, 'data-metadata-template-id={capture.metadata.templateId}'],
  [panelSource, 'data-backup-status={capture.backup.status}'],
  [panelSource, 'backupDestinationRoot:'],
  [panelSource, 'isBackupEnabled && backupDestinationRoot.trim()'],
  [panelSource, 'data-pinned={String(isPinned)}'],
  [panelSource, "setReviewMode('pinned')"],
  [panelSource, 'onOpenCapture?.(path)'],
  [panelSource, 'Invokes.DiscoverTetheredCameras'],
  [panelSource, 'Invokes.OpenTetherSession'],
  [panelSource, 'Invokes.CloseTetherSession'],
  [panelSource, 'Invokes.SetTetherCameraControl'],
  [panelSource, 'Invokes.TriggerTetherCapture'],
  [schemaSource, 'tetherDiscoveryResponseSchema'],
  [schemaSource, 'tetherCameraControlSchema'],
  [schemaSource, 'tetherCameraControlWriteRequestSchema'],
  [schemaSource, 'tetherCameraControlWriteResponseSchema'],
  [schemaSource, 'tetherSessionResponseSchema'],
  [schemaSource, 'tetherRecoverySummarySchema'],
  [schemaSource, 'tetherCaptureRequestSchema'],
  [schemaSource, 'tetherCaptureIngestSchema'],
  [schemaSource, 'wedding-copy-ingest'],
  [schemaSource, 'addTags'],
  [schemaSource, 'applyPresetIds'],
  [schemaSource, 'tetherCaptureBackupSchema'],
  [schemaSource, 'tetherCaptureMetadataSchema'],
  [schemaSource, 'tetherCaptureResponseSchema'],
  [schemaSource, 'cameraControlValues'],
  [registrySource, 'Panel.Tether'],
  [appPropertiesSource, "Tether = 'tether'"],
  [appPropertiesSource, "DiscoverTetheredCameras = 'discover_tethered_cameras'"],
  [appPropertiesSource, "OpenTetherSession = 'open_tether_session'"],
  [appPropertiesSource, "CloseTetherSession = 'close_tether_session'"],
  [appPropertiesSource, "SetTetherCameraControl = 'set_tether_camera_control'"],
  [appPropertiesSource, "TriggerTetherCapture = 'trigger_tether_capture'"],
  [libSource, 'tethering::discover_tethered_cameras'],
  [libSource, 'tethering::open_tether_session'],
  [libSource, 'tethering::close_tether_session'],
  [libSource, 'tethering::set_tether_camera_control'],
  [libSource, 'tethering::trigger_tether_capture'],
  [rustSource, 'fake_tether_provider_returns_one_ready_camera'],
  [rustSource, 'fake_provider_opens_and_closes_session'],
  [rustSource, 'fake_provider_captures_verified_raw_copy'],
  [rustSource, 'fake_provider_reports_backup_failure_without_losing_primary_capture'],
  [rustSource, 'session_open_quarantines_partial_downloads'],
  [rustSource, 'recover_tether_destination'],
  [rustSource, 'fake_provider_verifies_exposure_control_writes'],
  [rustSource, 'fake_provider_rejects_unsupported_exposure_control_values'],
  [rustSource, 'fake_camera_controls'],
  [rustSource, 'fake_provider_uses_collision_safe_ingest_counters'],
  [rustSource, 'fake_provider_applies_copyright_client_delivery_metadata_template'],
  [rustSource, 'fake_provider_applies_wedding_copy_ingest_preset'],
  [rustSource, 'apply_capture_import_preset'],
  [rustSource, '"tether_import_preset"'],
  [schemaSource, "'copyright-client-delivery'"],
  [panelSource, 'metadataTemplateCopyrightClientDelivery'],
  [rustSource, 'apply_capture_metadata_template'],
  [rustSource, '"copyright-client-delivery"'],
  [rustSource, 'write_verified_backup_capture'],
  [rustSource, 'tether_capture_artifacts'],
  [rustSource, 'resolve_imported_capture_path'],
  [rustSource, '"{source_stem}_{counter:04}"'],
  [rustSource, 'hardware_adapter_pending'],
  [panelSource, 'data-testid="tether-incoming-capture-strip"'],
  [panelSource, 'data-testid="tether-review-mode-control"'],
  [panelSource, 'data-review-mode-option={mode}'],
  [editorViewSource, 'handleTetherCaptureOpen'],
  [editorViewSource, 'handleImageSelect(path)'],
  [editorViewSource, 'onOpenCapture={(path) =>'],
  [visualSmokeSource, "data-opened-capture-path={openedCapturePath ?? ''}"],
  [visualSmokeScriptSource, '[data-review-mode-option="pinned"]'],
  [visualSmokeScriptSource, "getByTestId('tether-exposure-control-iso').selectOption('800')"],
  [visualSmokeScriptSource, 'data-testid="tether-recovery-status"][data-recovery-status="quarantined"'],
  [visualSmokeScriptSource, 'data-control-current-value="800"'],
  [visualSmokeSource, 'cameraControlValues: {'],
  [visualSmokeScriptSource, "selectOption('sourceSequence')"],
  [visualSmokeScriptSource, "selectOption('studioSession')"],
  [visualSmokeScriptSource, 'tether-backup-copy-toggle'],
  [visualSmokeScriptSource, 'data-ingest-preset-id="sourceSequence"'],
  [visualSmokeScriptSource, 'data-metadata-template-id="studioSession"'],
  [visualSmokeScriptSource, 'data-backup-status="verified"'],
  [visualSmokeScriptSource, '[data-testid="tether-incoming-capture-item"][data-pinned="true"]'],
  [visualSmokeScriptSource, 'data-opened-capture-path="/tmp/rawengine-tether-captures/alaska-dsc7853.ARW"'],
] as const;

const failures = requiredSnippets
  .filter(([source, snippet]) => !source.includes(snippet))
  .map(([, snippet]) => `missing marker: ${snippet}`);

for (const key of [
  'title',
  'subtitle',
  'refresh',
  'connected',
  'controlsRecorded',
  'controlVerified',
  'controlsReady',
  'controlsRequireSession',
  'capture',
  'captureBusy',
  'captureComplete',
  'captureVerified',
  'backupCopy',
  'backupCopyDescription',
  'backupCopyPlaceholder',
  'backupDisabled',
  'backupFailed',
  'backupVerified',
  'exposureControls',
  'ingestApplied',
  'ingestPreset',
  'ingestPresetCameraSequence',
  'ingestPresetSourceSequence',
  'ingestPresetTimestampCamera',
  'ingestPresetWeddingCopyIngest',
  'metadataApplied',
  'metadataSkipped',
  'metadataTemplate',
  'metadataTemplateCopyrightClientDelivery',
  'metadataTemplateNone',
  'metadataTemplateReviewSelect',
  'metadataTemplateStudioSession',
  'incomingCaptures',
  'reviewHoldCurrent',
  'reviewNewest',
  'reviewPinned',
  'pinCapture',
  'openCapture',
  'openSelectedCapture',
  'providerMode',
  'recoveryFailed',
  'recoveryQuarantined',
  'openSession',
  'closeSession',
  'sessionOpen',
  'sessionDestinationRoot',
  'sessionClosed',
  'noCameraTitle',
  'noCameraDescription',
]) {
  if (locale.editor?.tether?.[key] === undefined) failures.push(`missing locale: editor.tether.${key}`);
}

if (failures.length > 0) {
  console.error('tether discovery UI check failed');
  for (const failure of failures.slice(0, 12)) console.error(`- ${failure}`);
  process.exit(1);
}

console.log('tether discovery UI ok');
