import { agentChatTranscriptSchema, type AgentChatTranscript } from '../schemas/agentChatTranscriptSchemas';

const fixture = {
  artifactReview: {
    auditEntries: [
      {
        artifactId: 'artifact_edit_graph_patch_preview',
        id: 'audit-preview-artifact',
        replayLink: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
        stage: 'dry_run',
        summary: 'Dry-run preview is linked to the warning tool call and has not been applied.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_ai_subject_mask_alpha',
        id: 'audit-mask-artifact',
        replayLink: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
        stage: 'preview',
        summary: 'Subject mask preview is available for review before apply.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_ai_inpaint_preview_patch',
        id: 'audit-apply-blocked',
        replayLink: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
        stage: 'apply_blocked',
        summary: 'Apply remains blocked until replay approval exists.',
        toolCallId: 'tool-3',
      },
    ],
    beforeAfter: {
      afterLabel: 'Dry-run preview',
      afterRevision: 'graph_rev_45_preview',
      beforeLabel: 'Current edit graph',
      beforeRevision: 'graph_rev_44',
    },
    previewArtifacts: [
      {
        contentHash: 'sha256:2f0c9d81a77b4e51',
        id: 'artifact_edit_graph_patch_preview',
        kind: 'edit_preview',
        source: 'output.previewArtifacts',
        status: 'review_required',
        title: 'Tone/color preview',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:74d6ae13b5c20e9f',
        id: 'artifact_ai_subject_mask_alpha',
        kind: 'mask_preview',
        source: 'output.maskArtifacts',
        status: 'ready',
        title: 'Protected subject mask',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:5a42f8c0e73d912b',
        id: 'artifact_ai_inpaint_preview_patch',
        kind: 'clipping_map',
        source: 'auditLog.affectedArtifactIds',
        status: 'audit_only',
        title: 'Highlight warning map',
        toolCallId: 'tool-3',
      },
    ],
  },
  auditTranscript: {
    evidenceTier: 'schema_only',
    finalRevision: 'graph_rev_45_preview',
    initialRevision: 'graph_rev_44',
    records: [
      {
        artifactLinks: [],
        id: 'audit-record-tool-1',
        outcome: 'success',
        requestHash: 'sha256:48f0c2c8332bb2f7',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
        stage: 'read',
        summary: 'Read available app-server edit surfaces before proposing changes.',
        timestamp: '14:22:15',
        title: 'Read available edit tools',
        toolCallId: 'tool-1',
        toolName: 'rawengine.route_catalog',
        warnings: [],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
            id: 'artifact_edit_graph_patch_preview',
            label: 'Tone/color preview',
          },
          {
            href: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
            id: 'artifact_ai_subject_mask_alpha',
            label: 'Protected subject mask',
          },
        ],
        id: 'audit-record-tool-2',
        outcome: 'warning',
        requestHash: 'sha256:a84094d362ed80af',
        schema: 'toneColorCommandEnvelope.v1',
        stage: 'dry_run',
        summary: 'Prepared a non-mutating dry-run with review artifacts.',
        timestamp: '14:22:18',
        title: 'Build color dry-run',
        toolCallId: 'tool-2',
        toolName: 'rawengine.tone_color.dry_run',
        warnings: ['Review the highlight clipping map before apply.'],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html#artifact-hash-proof',
            id: 'artifact_ai_inpaint_preview_patch',
            label: 'Highlight warning map',
          },
        ],
        id: 'audit-record-tool-3',
        outcome: 'blocked',
        requestHash: 'sha256:de0fb74e411dc332',
        schema: 'aiEnhancementApplyRequest.v1',
        stage: 'apply',
        summary: 'Apply was blocked because runtime replay approval is unavailable.',
        timestamp: '14:22:20',
        title: 'Apply proposed grade',
        toolCallId: 'tool-3',
        toolName: 'rawengine.edit.apply_dry_run_plan',
        warnings: ['UI-only shell: no project mutation.'],
      },
    ],
    replayRoot: 'docs/validation/agent-replay-proof-gallery-2026-06-16.html',
    schemaVersion: 1,
    targetLabel: 'DSC_1042.ARW',
  },
  dryRunReview: {
    actions: [
      {
        id: 'approve-dry-run',
        label: 'Approve plan',
        reason: 'Requires runtime replay before apply can be enabled.',
        state: 'available',
      },
      {
        id: 'reject-plan',
        label: 'Reject plan',
        reason: 'Rejected state is visible and audit-only in this fixture.',
        state: 'available',
      },
      {
        id: 'apply-unavailable',
        label: 'Apply unavailable',
        reason: 'UI-only demo cannot mutate project state.',
        state: 'unavailable',
      },
    ],
    affectedTargets: [
      {
        id: 'current-frame',
        label: 'Frame',
        value: 'DSC_1042.ARW',
      },
      {
        id: 'sidecar',
        label: 'Sidecar',
        value: 'Pending dry-run artifact',
      },
      {
        id: 'mask',
        label: 'Mask',
        value: 'Protected subject mask',
      },
    ],
    parameterDiffs: [
      {
        after: '+420 K',
        before: '+0 K',
        id: 'temperature',
        label: 'Temperature',
      },
      {
        after: '-18',
        before: '0',
        id: 'highlights',
        label: 'Highlights',
      },
      {
        after: '+7',
        before: '0',
        id: 'subject-saturation',
        label: 'Subject saturation',
      },
    ],
    warnings: [
      'Window highlight clipping must be reviewed before apply.',
      'Runtime apply stays disabled until app-server replay proof exists.',
    ],
  },
  id: 'agent-chat-demo-portrait-grade-v1',
  messages: [
    {
      body: 'Warm the skin, keep the dress neutral, and do not clip the window highlights.',
      id: 'msg-user-1',
      role: 'user',
      timestamp: '14:22:10',
    },
    {
      body: 'I can prepare a dry-run with color balance, highlight recovery, and a protected subject mask.',
      id: 'msg-agent-1',
      role: 'assistant',
      timestamp: '14:22:14',
    },
    {
      body: 'Dry-run only. No pixels or sidecars have been changed.',
      id: 'msg-system-1',
      role: 'system',
      timestamp: '14:22:16',
    },
  ],
  runtimeStatus: 'ui_only_demo',
  sessionTitle: 'Portrait color grade',
  toolCalls: [
    {
      approvalState: 'not_required',
      durationMs: 184,
      id: 'tool-1',
      mode: 'read',
      provenance: {
        requestHash: 'sha256:48f0c2c8332bb2f7',
        runtime: 'codex_app_server',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
      },
      status: 'succeeded',
      summary: 'Found tone, color, mask, and export routes.',
      timestamp: '14:22:15',
      title: 'Read available edit tools',
      toolName: 'rawengine.route_catalog',
    },
    {
      approvalState: 'required',
      durationMs: 312,
      id: 'tool-2',
      mode: 'dry_run',
      provenance: {
        requestHash: 'sha256:a84094d362ed80af',
        runtime: 'codex_app_server',
        schema: 'toneColorCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'warning',
      summary: 'Prepared +420 K warmth, -18 highlights, and subject-safe saturation.',
      timestamp: '14:22:18',
      title: 'Build color dry-run',
      toolName: 'rawengine.tone_color.dry_run',
      warning: 'Window highlight warning: review clipping map before apply.',
    },
    {
      approvalState: 'rejected',
      id: 'tool-3',
      mode: 'apply',
      provenance: {
        requestHash: 'sha256:de0fb74e411dc332',
        runtime: 'codex_app_server',
        schema: 'aiEnhancementApplyRequest.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'blocked',
      summary: 'Apply blocked until the dry-run diff is inspected and approved.',
      timestamp: '14:22:20',
      title: 'Apply proposed grade',
      toolName: 'rawengine.edit.apply_dry_run_plan',
      warning: 'UI-only shell: this demo does not mutate project state.',
    },
  ],
} satisfies AgentChatTranscript;

export const agentChatTranscriptFixture = agentChatTranscriptSchema.parse(fixture);
