import { agentChatTranscriptSchema, type AgentChatTranscript } from '../schemas/agentChatTranscriptSchemas';

const fixture = {
  artifactReview: {
    auditEntries: [
      {
        artifactId: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
        id: 'audit-preview-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'dry_run',
        summary: 'Dry-run preview is linked to the accepted runtime demo workflow.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_agent_expert_edit_demo_before_raw_2844',
        id: 'audit-before-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'preview',
        summary: 'Before RAW preview artifact is captured for comparison.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
        id: 'audit-after-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'preview',
        summary: 'After virtual-copy preview artifact is captured after approved apply.',
        toolCallId: 'tool-3',
      },
    ],
    beforeAfter: {
      afterLabel: 'Applied virtual copy',
      afterRevision: 'graph_rev_agent_expert_edit_demo_initial_2844:apply:command_agent_expert_edit_demo_apply_2844',
      beforeLabel: 'Current edit graph',
      beforeRevision: 'graph_rev_agent_expert_edit_demo_initial_2844',
    },
    previewArtifacts: [
      {
        contentHash: 'sha256:2f0c9d81a77b4e51',
        id: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
        kind: 'edit_preview',
        source: 'output.previewArtifacts',
        status: 'ready',
        title: 'Tone/color preview',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:74d6ae13b5c20e9f',
        id: 'artifact_agent_expert_edit_demo_before_raw_2844',
        kind: 'edit_preview',
        source: 'auditLog.affectedArtifactIds',
        status: 'ready',
        title: 'Before RAW preview',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:5a42f8c0e73d912b',
        id: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
        kind: 'edit_preview',
        source: 'auditLog.affectedArtifactIds',
        status: 'ready',
        title: 'After virtual-copy preview',
        toolCallId: 'tool-3',
      },
    ],
  },
  auditTranscript: {
    evidenceTier: 'runtime_apply_demo',
    finalRevision: 'graph_rev_agent_expert_edit_demo_initial_2844:apply:command_agent_expert_edit_demo_apply_2844',
    initialRevision: 'graph_rev_agent_expert_edit_demo_initial_2844',
    records: [
      {
        artifactLinks: [],
        id: 'audit-record-tool-1',
        outcome: 'success',
        requestHash: 'sha256:48f0c2c8332bb2f7',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
        stage: 'read',
        summary: 'Inspected available app-server edit surfaces before proposing changes.',
        timestamp: '14:22:15',
        title: 'Read available edit tools',
        toolCallId: 'tool-1',
        toolName: 'rawengine.route_catalog',
        warnings: [],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
            label: 'Tone/color preview',
          },
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_before_raw_2844',
            label: 'Before RAW preview',
          },
        ],
        id: 'audit-record-tool-2',
        outcome: 'warning',
        requestHash: 'sha256:a84094d362ed80af',
        schema: 'toneColorCommandEnvelope.v1',
        stage: 'dry_run',
        summary: 'Prepared a non-mutating dry-run with review artifacts.',
        timestamp: '14:22:18',
        title: 'Build color dry-run',
        toolCallId: 'tool-2',
        toolName: 'rawengine.tone_color.dry_run',
        warnings: ['Review the highlight clipping map before apply.'],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
            label: 'After virtual-copy preview',
          },
        ],
        id: 'audit-record-tool-3',
        outcome: 'success',
        requestHash: 'sha256:de0fb74e411dc332',
        schema: 'aiEnhancementApplyRequest.v1',
        stage: 'apply',
        summary: 'Applied the approved deterministic dry-run to the virtual-copy edit graph.',
        timestamp: '14:22:20',
        title: 'Apply proposed grade',
        toolCallId: 'tool-3',
        toolName: 'tonecolor.apply_command',
        warnings: [],
      },
      {
        artifactLinks: [],
        id: 'audit-record-tool-4',
        outcome: 'blocked',
        requestHash: 'sha256:8fb67d92a0e2f416',
        schema: 'aiEnhancementCommandEnvelope.v1',
        stage: 'dry_run',
        summary: 'Rejected an unavailable AI connector before any pixel upload, preview generation, or graph mutation.',
        timestamp: '14:22:24',
        title: 'Reject unavailable provider',
        toolCallId: 'tool-4',
        toolName: 'rawengine.ai.enhancement.dry_run',
        warnings: ['AI provider missing-local-connector is unavailable; no pixels were sent and no edit was applied.'],
      },
    ],
    replayRoot: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
    schemaVersion: 1,
    targetLabel: 'DSC_2844.NEF',
  },
  dryRunReview: {
    actions: [
      {
        id: 'approve-dry-run',
        label: 'Approve plan',
        reason: 'Runtime demo replay accepted this dry-run before apply.',
        state: 'available',
      },
      {
        id: 'reject-plan',
        label: 'Reject plan',
        reason: 'Rejected state is visible and audit-only in this fixture.',
        state: 'available',
      },
      {
        id: 'apply-approved',
        label: 'Apply approved',
        reason: 'Matching dry-run was accepted and applied to a virtual copy.',
        state: 'available',
      },
    ],
    affectedTargets: [
      {
        id: 'current-frame',
        label: 'Frame',
        value: 'DSC_2844.NEF',
      },
      {
        id: 'sidecar',
        label: 'Sidecar',
        value: 'Virtual copy sidecar',
      },
      {
        id: 'mask',
        label: 'Mask',
        value: 'Original RAW unchanged',
      },
    ],
    parameterDiffs: [
      {
        after: '+420 K',
        before: '+0 K',
        id: 'temperature',
        label: 'Temperature',
      },
      {
        after: '-18',
        before: '0',
        id: 'highlights',
        label: 'Highlights',
      },
      {
        after: '+7',
        before: '0',
        id: 'subject-saturation',
        label: 'Subject saturation',
      },
    ],
    warnings: [
      'Window highlight clipping must be reviewed before apply.',
      'Original RAW is never overwritten; apply targets a virtual copy.',
    ],
  },
  id: 'agent-chat-demo-expert-edit-runtime-v1',
  livePromptWalkthrough: {
    approval: {
      label: 'Approved dry-run',
      state: 'approved',
      summary: 'The dry-run was accepted before apply; the apply step targets only the virtual-copy edit graph.',
    },
    id: 'agent-live-prompt-walkthrough-runtime-2844',
    planSummary: 'Inspect local tools, build a tone/color dry-run, wait for approval, then apply the accepted plan.',
    prompt:
      'Inspect DSC_2844.NEF, warm the scene, lift shadows, protect highlights, preview it, then apply if approved.',
    stages: [
      {
        id: 'prompt',
        label: 'Prompt received',
        state: 'completed',
        summary: 'The user request is captured as the session intent for the selected RAW frame.',
      },
      {
        id: 'inspect',
        label: 'Inspect tools and frame',
        state: 'completed',
        summary: 'The app-server route catalog and selected-frame scope are inspected before planning.',
        toolCallId: 'tool-1',
      },
      {
        id: 'dry-run',
        label: 'Stage dry-run',
        state: 'completed',
        summary: 'A non-mutating tone/color dry-run is prepared with before/after artifacts.',
        toolCallId: 'tool-2',
      },
      {
        id: 'approval',
        label: 'Approval accepted',
        state: 'completed',
        summary: 'The review gate accepts the exact dry-run before any edit graph mutation.',
        toolCallId: 'tool-2',
      },
      {
        id: 'apply',
        label: 'Apply accepted plan',
        state: 'completed',
        summary: 'The approved command is applied to the virtual-copy edit graph and linked to audit evidence.',
        toolCallId: 'tool-3',
      },
    ],
    targetLabel: 'DSC_2844.NEF -> virtual copy',
  },
  messages: [
    {
      body: 'Inspect DSC_2844.NEF, warm the scene, lift shadows, protect highlights, preview it, then apply if approved.',
      id: 'msg-user-1',
      role: 'user',
      timestamp: '14:22:10',
    },
    {
      body: 'I can inspect the available app-server tools, prepare a dry-run, and apply it to a virtual copy after approval.',
      id: 'msg-agent-1',
      role: 'assistant',
      timestamp: '14:22:14',
    },
    {
      body: 'Runtime demo apply complete. The original RAW was not overwritten.',
      id: 'msg-system-1',
      role: 'system',
      timestamp: '14:22:16',
    },
    {
      body: 'The requested connector is unavailable, so I stopped that AI edit before sending pixels or changing the image.',
      id: 'msg-system-2',
      role: 'system',
      timestamp: '14:22:24',
    },
  ],
  privateRawArtifacts: {
    artifactCount: 5,
    fixtureId: 'validation.raw-open-edit-export.high-iso-skin-shadow.v1',
    issue: 3033,
    reportPath: 'docs/validation/agent-app-server-private-raw-artifacts-2026-06-20.json',
    sourceHashUnchanged: true,
    status: 'partial_agent_apply_plus_private_raw_artifacts',
    title: 'Private RAW artifact lane',
    validationMode: 'agent_app_server_bridge_plus_private_raw_artifact_proof',
    workflowReportPath: 'private-artifacts/validation/open-edit-export/high-iso-skin-shadow-v1-workflow-report.json',
  },
  reviewHandoff: {
    afterArtifactId: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
    afterLabel: 'After',
    approvalLabel: 'Approved dry-run',
    approvalState: 'approved',
    auditArtifactId: 'audit-record-tool-3',
    auditLabel: 'Audit',
    auditTrail: [
      {
        approvalState: 'not_required',
        artifactIds: [],
        id: 'handoff-audit-tool-1',
        stage: 'read',
        toolCallId: 'tool-1',
        toolName: 'rawengine.route_catalog',
      },
      {
        approvalState: 'required',
        artifactIds: [
          'artifact_agent_expert_edit_demo_preview_dry_run_2844',
          'artifact_agent_expert_edit_demo_before_raw_2844',
        ],
        id: 'handoff-audit-tool-2',
        stage: 'dry_run',
        toolCallId: 'tool-2',
        toolName: 'rawengine.tone_color.dry_run',
      },
      {
        approvalState: 'approved',
        artifactIds: ['artifact_agent_expert_edit_demo_after_virtual_copy_2844'],
        id: 'handoff-audit-tool-3',
        stage: 'apply',
        toolCallId: 'tool-3',
        toolName: 'tonecolor.apply_command',
      },
    ],
    beforeArtifactId: 'artifact_agent_expert_edit_demo_before_raw_2844',
    beforeLabel: 'Before',
    commandSummary: 'Warm scene, lift shadows, protect highlights, and apply to a virtual-copy edit graph.',
    id: 'agent-review-handoff-runtime-2844',
    nextAction: 'Open the proof gallery, compare before/after, or rollback the virtual-copy revision.',
    outputProof: {
      contentHash: 'sha256:5a42f8c0e73d912b',
      href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
      label: 'Runtime proof gallery',
      status: 'runtime_apply_verified',
    },
    rollback: {
      label: 'Rollback virtual copy',
      status: 'available',
      summary: 'Rollback restores graph_rev_agent_expert_edit_demo_initial_2844 without modifying the source RAW.',
      targetRevision: 'graph_rev_agent_expert_edit_demo_initial_2844',
    },
    title: 'Before/after handoff',
  },
  runtimeStatus: 'runtime_apply_demo',
  selectedFrameScope: {
    approvalLabel: 'Approval required before apply',
    approvalState: 'required',
    auditArtifactId: 'audit-record-tool-2',
    dryRunToolCallId: 'tool-2',
    excludedAssets: [
      {
        id: 'excluded-adjacent-frame',
        label: 'Excluded frame',
        reason: 'Not selected for this expert edit request.',
        value: 'DSC_2845.NEF',
      },
      {
        id: 'excluded-original-raw',
        label: 'Source RAW',
        reason: 'Source pixels remain immutable; only edit graph and virtual-copy sidecar are targeted.',
        value: 'DSC_2844.NEF',
      },
    ],
    id: 'agent-selected-frame-scope-runtime-2844',
    noOverwriteTarget: {
      label: 'No-overwrite target',
      summary:
        'Apply path writes the accepted command to a virtual-copy edit graph and leaves source RAW bytes unchanged.',
      value: 'Virtual copy sidecar',
    },
    policyChecks: [
      {
        id: 'single-selected-frame',
        label: 'One selected frame',
        state: 'passed',
      },
      {
        id: 'source-raw-immutable',
        label: 'Original RAW protected',
        state: 'passed',
      },
      {
        id: 'highlight-review-required',
        label: 'Highlight clipping review',
        state: 'review_required',
      },
    ],
    proofHref: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
    proofLabel: 'Dry-run proof',
    selectedAssets: [
      {
        id: 'selected-active-frame',
        label: 'Selected frame',
        role: 'active RAW input',
        stateLabel: 'Selected',
        value: 'DSC_2844.NEF',
      },
      {
        id: 'selected-virtual-copy',
        label: 'Write target',
        role: 'editable virtual copy',
        stateLabel: 'Selected',
        value: 'graph_rev_agent_expert_edit_demo_initial_2844:virtual-copy',
      },
    ],
    summary: 'Dry-run scope is limited to the active RAW frame and its virtual-copy edit graph.',
    title: 'Selected-frame scope',
  },
  sessionTitle: 'Expert RAW edit demo',
  toolCalls: [
    {
      approvalState: 'not_required',
      durationMs: 184,
      id: 'tool-1',
      mode: 'read',
      provenance: {
        requestHash: 'sha256:48f0c2c8332bb2f7',
        runtime: 'codex_app_server',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
      },
      status: 'succeeded',
      summary: 'Found tone, color, and app-server routes.',
      timestamp: '14:22:15',
      title: 'Read available edit tools',
      toolName: 'rawengine.route_catalog',
    },
    {
      approvalState: 'required',
      durationMs: 312,
      id: 'tool-2',
      mode: 'dry_run',
      provenance: {
        requestHash: 'sha256:a84094d362ed80af',
        runtime: 'codex_app_server',
        schema: 'toneColorCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'warning',
      summary: 'Prepared warmth, +20 shadows, -22 highlights, and safe saturation.',
      timestamp: '14:22:18',
      title: 'Build color dry-run',
      toolName: 'rawengine.tone_color.dry_run',
      warning: 'Window highlight warning: review clipping map before apply.',
    },
    {
      approvalState: 'approved',
      id: 'tool-3',
      mode: 'apply',
      provenance: {
        requestHash: 'sha256:de0fb74e411dc332',
        runtime: 'codex_app_server',
        schema: 'toneColorCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'succeeded',
      summary: 'Applied the accepted dry-run to the virtual-copy edit graph.',
      timestamp: '14:22:20',
      title: 'Apply proposed grade',
      toolName: 'tonecolor.apply_command',
    },
    {
      approvalState: 'rejected',
      durationMs: 41,
      id: 'tool-4',
      mode: 'dry_run',
      provenance: {
        requestHash: 'sha256:8fb67d92a0e2f416',
        runtime: 'codex_app_server',
        schema: 'aiEnhancementCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'blocked',
      summary:
        'Provider missing-local-connector is unavailable; dry-run stopped before any image data left the machine.',
      timestamp: '14:22:24',
      title: 'Reject unavailable provider',
      toolName: 'rawengine.ai.enhancement.dry_run',
      warning: 'No pixels were sent and no edit was applied.',
    },
  ],
} satisfies AgentChatTranscript;

export const agentChatTranscriptFixture = agentChatTranscriptSchema.parse(fixture);
