import { agentChatTranscriptSchema, type AgentChatTranscript } from '../schemas/agentChatTranscriptSchemas';

const fixture = {
  artifactReview: {
    auditEntries: [
      {
        artifactId: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
        id: 'audit-preview-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'dry_run',
        summary: 'Dry-run preview is linked to the accepted runtime demo workflow.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_agent_expert_edit_demo_before_raw_2844',
        id: 'audit-before-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'preview',
        summary: 'Before RAW preview artifact is captured for comparison.',
        toolCallId: 'tool-2',
      },
      {
        artifactId: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
        id: 'audit-after-artifact',
        replayLink: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
        stage: 'preview',
        summary: 'After virtual-copy preview artifact is captured after approved apply.',
        toolCallId: 'tool-3',
      },
    ],
    beforeAfter: {
      afterLabel: 'Applied virtual copy',
      afterRevision: 'graph_rev_agent_expert_edit_demo_initial_2844:apply:command_agent_expert_edit_demo_apply_2844',
      beforeLabel: 'Current edit graph',
      beforeRevision: 'graph_rev_agent_expert_edit_demo_initial_2844',
    },
    previewArtifacts: [
      {
        contentHash: 'sha256:2f0c9d81a77b4e51',
        id: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
        kind: 'edit_preview',
        source: 'output.previewArtifacts',
        status: 'ready',
        title: 'Tone/color preview',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:74d6ae13b5c20e9f',
        id: 'artifact_agent_expert_edit_demo_before_raw_2844',
        kind: 'edit_preview',
        source: 'auditLog.affectedArtifactIds',
        status: 'ready',
        title: 'Before RAW preview',
        toolCallId: 'tool-2',
      },
      {
        contentHash: 'sha256:5a42f8c0e73d912b',
        id: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
        kind: 'edit_preview',
        source: 'auditLog.affectedArtifactIds',
        status: 'ready',
        title: 'After virtual-copy preview',
        toolCallId: 'tool-3',
      },
    ],
  },
  auditTranscript: {
    evidenceTier: 'runtime_apply_demo',
    finalRevision: 'graph_rev_agent_expert_edit_demo_initial_2844:apply:command_agent_expert_edit_demo_apply_2844',
    initialRevision: 'graph_rev_agent_expert_edit_demo_initial_2844',
    records: [
      {
        artifactLinks: [],
        id: 'audit-record-tool-1',
        outcome: 'success',
        requestHash: 'sha256:48f0c2c8332bb2f7',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
        stage: 'read',
        summary: 'Inspected available app-server edit surfaces before proposing changes.',
        timestamp: '14:22:15',
        title: 'Read available edit tools',
        toolCallId: 'tool-1',
        toolName: 'rawengine.route_catalog',
        warnings: [],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_preview_dry_run_2844',
            label: 'Tone/color preview',
          },
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_before_raw_2844',
            label: 'Before RAW preview',
          },
        ],
        id: 'audit-record-tool-2',
        outcome: 'warning',
        requestHash: 'sha256:a84094d362ed80af',
        schema: 'toneColorCommandEnvelope.v1',
        stage: 'dry_run',
        summary: 'Prepared a non-mutating dry-run with review artifacts.',
        timestamp: '14:22:18',
        title: 'Build color dry-run',
        toolCallId: 'tool-2',
        toolName: 'rawengine.tone_color.dry_run',
        warnings: ['Review the highlight clipping map before apply.'],
      },
      {
        artifactLinks: [
          {
            href: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
            id: 'artifact_agent_expert_edit_demo_after_virtual_copy_2844',
            label: 'After virtual-copy preview',
          },
        ],
        id: 'audit-record-tool-3',
        outcome: 'success',
        requestHash: 'sha256:de0fb74e411dc332',
        schema: 'aiEnhancementApplyRequest.v1',
        stage: 'apply',
        summary: 'Applied the approved deterministic dry-run to the virtual-copy edit graph.',
        timestamp: '14:22:20',
        title: 'Apply proposed grade',
        toolCallId: 'tool-3',
        toolName: 'tonecolor.apply_command',
        warnings: [],
      },
    ],
    replayRoot: 'docs/validation/agent-expert-edit-demo-workflow-2026-06-21.html',
    schemaVersion: 1,
    targetLabel: 'DSC_2844.NEF',
  },
  dryRunReview: {
    actions: [
      {
        id: 'approve-dry-run',
        label: 'Approve plan',
        reason: 'Runtime demo replay accepted this dry-run before apply.',
        state: 'available',
      },
      {
        id: 'reject-plan',
        label: 'Reject plan',
        reason: 'Rejected state is visible and audit-only in this fixture.',
        state: 'available',
      },
      {
        id: 'apply-approved',
        label: 'Apply approved',
        reason: 'Matching dry-run was accepted and applied to a virtual copy.',
        state: 'available',
      },
    ],
    affectedTargets: [
      {
        id: 'current-frame',
        label: 'Frame',
        value: 'DSC_2844.NEF',
      },
      {
        id: 'sidecar',
        label: 'Sidecar',
        value: 'Virtual copy sidecar',
      },
      {
        id: 'mask',
        label: 'Mask',
        value: 'Original RAW unchanged',
      },
    ],
    parameterDiffs: [
      {
        after: '+420 K',
        before: '+0 K',
        id: 'temperature',
        label: 'Temperature',
      },
      {
        after: '-18',
        before: '0',
        id: 'highlights',
        label: 'Highlights',
      },
      {
        after: '+7',
        before: '0',
        id: 'subject-saturation',
        label: 'Subject saturation',
      },
    ],
    warnings: [
      'Window highlight clipping must be reviewed before apply.',
      'Original RAW is never overwritten; apply targets a virtual copy.',
    ],
  },
  id: 'agent-chat-demo-expert-edit-runtime-v1',
  messages: [
    {
      body: 'Inspect DSC_2844.NEF, warm the scene, lift shadows, protect highlights, preview it, then apply if approved.',
      id: 'msg-user-1',
      role: 'user',
      timestamp: '14:22:10',
    },
    {
      body: 'I can inspect the available app-server tools, prepare a dry-run, and apply it to a virtual copy after approval.',
      id: 'msg-agent-1',
      role: 'assistant',
      timestamp: '14:22:14',
    },
    {
      body: 'Runtime demo apply complete. The original RAW was not overwritten.',
      id: 'msg-system-1',
      role: 'system',
      timestamp: '14:22:16',
    },
  ],
  runtimeStatus: 'runtime_apply_demo',
  sessionTitle: 'Expert RAW edit demo',
  toolCalls: [
    {
      approvalState: 'not_required',
      durationMs: 184,
      id: 'tool-1',
      mode: 'read',
      provenance: {
        requestHash: 'sha256:48f0c2c8332bb2f7',
        runtime: 'codex_app_server',
        schema: 'rawEngineAppServerRouteCatalogRequest.v1',
      },
      status: 'succeeded',
      summary: 'Found tone, color, and app-server routes.',
      timestamp: '14:22:15',
      title: 'Read available edit tools',
      toolName: 'rawengine.route_catalog',
    },
    {
      approvalState: 'required',
      durationMs: 312,
      id: 'tool-2',
      mode: 'dry_run',
      provenance: {
        requestHash: 'sha256:a84094d362ed80af',
        runtime: 'codex_app_server',
        schema: 'toneColorCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'warning',
      summary: 'Prepared warmth, +20 shadows, -22 highlights, and safe saturation.',
      timestamp: '14:22:18',
      title: 'Build color dry-run',
      toolName: 'rawengine.tone_color.dry_run',
      warning: 'Window highlight warning: review clipping map before apply.',
    },
    {
      approvalState: 'approved',
      id: 'tool-3',
      mode: 'apply',
      provenance: {
        requestHash: 'sha256:de0fb74e411dc332',
        runtime: 'codex_app_server',
        schema: 'toneColorCommandEnvelope.v1',
        sourceAssetHash: 'sha256:9d0f83a746a7d4e6',
      },
      status: 'succeeded',
      summary: 'Applied the accepted dry-run to the virtual-copy edit graph.',
      timestamp: '14:22:20',
      title: 'Apply proposed grade',
      toolName: 'tonecolor.apply_command',
    },
  ],
} satisfies AgentChatTranscript;

export const agentChatTranscriptFixture = agentChatTranscriptSchema.parse(fixture);
