import { aiAppServerToolRouteManifestSchema, type AiAppServerToolRoute } from '../schemas/aiAppServerToolRouteSchemas';

export const AI_APP_SERVER_TOOL_ROUTE_MANIFEST = aiAppServerToolRouteManifestSchema.parse({
  routes: [
    {
      appServerToolName: 'ai.mask.dry_run_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiToolDryRunResultV1',
      reason: 'Subject-mask generation is represented by the typed AI mask dry-run tool.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'generate_ai_subject_mask',
      status: 'mapped',
      toolCapability: 'subject_mask',
    },
    {
      appServerToolName: 'ai.mask.dry_run_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiToolDryRunResultV1',
      reason: 'Subject-mask precompute feeds the same dry-run tool surface before UI apply.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'precompute_ai_subject_mask',
      status: 'mapped',
      toolCapability: 'subject_mask',
    },
    {
      appServerToolName: 'ai.mask.dry_run_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiToolDryRunResultV1',
      reason: 'Depth mask generation is supported by the typed AI mask dry-run tool capability set.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'generate_ai_depth_mask',
      status: 'mapped',
      toolCapability: 'depth_mask',
    },
    {
      appServerToolName: 'ai.mask.dry_run_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiToolDryRunResultV1',
      reason: 'Foreground mask generation is supported by the typed AI mask dry-run tool capability set.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'generate_ai_foreground_mask',
      status: 'mapped',
      toolCapability: 'foreground_mask',
    },
    {
      appServerToolName: 'ai.mask.dry_run_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiToolDryRunResultV1',
      reason: 'Sky mask generation is supported by the typed AI mask dry-run tool capability set.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'generate_ai_sky_mask',
      status: 'mapped',
      toolCapability: 'sky_mask',
    },
    {
      appServerToolName: 'ai.mask.apply_subject',
      commandSchemaName: 'AiToolCommandEnvelopeV1',
      executionMode: 'apply_dry_run_plan',
      outputSchemaName: 'AiToolApplyResultV1',
      reason: 'Accepted AI mask dry-run plans apply through the typed app-server tool surface.',
      sourceKind: 'app_server_tool',
      sourceOperation: 'ai.mask.apply_subject',
      status: 'mapped',
      toolCapability: 'subject_mask',
    },
    {
      appServerToolName: 'ai.enhancement.dry_run_command',
      commandSchemaName: 'AiEnhancementCommandEnvelopeV1',
      executionMode: 'dry_run_command',
      outputSchemaName: 'AiEnhancementDryRunResultV1',
      reason: 'Generative inpaint preview maps to the typed AI enhancement dry-run tool before apply approval.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'invoke_generative_replace',
      status: 'mapped',
      toolCapability: 'inpaint',
    },
    {
      appServerToolName: 'ai.enhancement.apply_command',
      commandSchemaName: 'AiEnhancementCommandEnvelopeV1',
      executionMode: 'apply_dry_run_plan',
      outputSchemaName: 'AiEnhancementApplyResultV1',
      reason:
        'Mask-definition generative inpaint mutates the edit graph and maps to the typed enhancement apply tool; dry-run parity remains tracked separately.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'invoke_generative_replace_with_mask_def',
      status: 'mapped',
      toolCapability: 'inpaint',
    },
    {
      reason: 'Connector health is a capability/status probe, not an image edit tool call.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'check_ai_connector_status',
      status: 'connector_status',
    },
    {
      reason: 'Connector test is a settings validation probe, not an image edit tool call.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'test_ai_connector_connection',
      status: 'connector_status',
    },
    {
      reason: 'AI tag cleanup mutates library metadata and is tracked outside image-edit app-server tools.',
      sourceKind: 'tauri_invoke',
      sourceOperation: 'clear_ai_tags',
      status: 'metadata_cleanup',
    },
  ],
  schemaVersion: 1,
});

export const AI_APP_SERVER_TOOL_ROUTES: ReadonlyArray<AiAppServerToolRoute> = AI_APP_SERVER_TOOL_ROUTE_MANIFEST.routes;
