import {
  ActorKind,
  ApprovalClass,
  RAW_ENGINE_SCHEMA_VERSION,
  artifactHandleV1Schema,
  commandEnvelopeV1Schema,
  negativeLabCommandEnvelopeV1Schema,
  negativeAcquisitionProfileV1Schema,
  negativeRollSessionV1Schema,
  panoramaArtifactV1Schema,
  queryEnvelopeV1Schema,
  rawEngineToolRegistryV1Schema,
  type ArtifactHandleV1,
  type CommandEnvelopeV1,
  type NegativeAcquisitionProfileV1,
  type NegativeLabCommandEnvelopeV1,
  type NegativeRollSessionV1,
  type PanoramaArtifactV1,
  type QueryEnvelopeV1,
  type RawEngineToolRegistryV1,
} from './rawEngineSchemas.js';

export const sampleQueryEnvelopeV1: QueryEnvelopeV1 = queryEnvelopeV1Schema.parse({
  actor: {
    id: 'codex-app-server',
    kind: ActorKind.Agent,
    sessionId: 'session_sample',
  },
  correlationId: 'corr_metadata_sample',
  parameters: {
    includeExif: true,
  },
  queryId: 'query_metadata_sample',
  queryType: 'image.getMetadata',
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  target: {
    imagePath: '/photos/session/IMG_0001.CR3',
    kind: 'image',
  },
});

export const sampleCommandEnvelopeV1: CommandEnvelopeV1 = commandEnvelopeV1Schema.parse({
  actor: {
    id: 'codex-app-server',
    kind: ActorKind.Agent,
    sessionId: 'session_sample',
  },
  approval: {
    approvalClass: ApprovalClass.PreviewOnly,
    reason: 'Tone dry-run does not persist sidecars or exported files.',
    state: 'not_required',
  },
  commandId: 'command_tone_dry_run_sample',
  commandType: 'edit.tone.dryRun',
  correlationId: 'corr_tone_dry_run_sample',
  dryRun: true,
  expectedGraphRevision: 'graph_rev_42',
  parameters: {
    exposureEv: 0.25,
    highlights: -12,
  },
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  target: {
    imagePath: '/photos/session/IMG_0001.CR3',
    kind: 'image',
    virtualCopyId: null,
  },
});

export const sampleArtifactHandleV1: ArtifactHandleV1 = artifactHandleV1Schema.parse({
  artifactId: 'artifact_preview_sample',
  contentHash: 'sha256:sample-preview-hash',
  dimensions: {
    height: 1080,
    width: 1620,
  },
  kind: 'preview',
  storage: 'temp_cache',
});

export const sampleToolRegistryV1: RawEngineToolRegistryV1 = rawEngineToolRegistryV1Schema.parse({
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  tools: [
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'QueryEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ImageMetadataResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'image.get_metadata',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'CommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ToneDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'edit.dry_run_tone',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'NegativeLabCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'NegativeLabDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'negativelab.convert_frames',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'NegativeLabCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'NegativeRollSessionV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'negativelab.apply_command',
    },
  ],
});

export const samplePanoramaArtifactV1: PanoramaArtifactV1 = panoramaArtifactV1Schema.parse({
  alignment: {
    algorithmId: 'rapidraw_fast9_brief_ransac_v1',
    downscaleMaxDimensionPx: 1600,
    globalHomographyCount: 3,
    minimumInliersForConnection: 15,
    pairwiseMatches: [
      {
        fromSourceIndex: 0,
        homography3x3: [1, 0.01, 148.2, -0.01, 1, 2.4, 0, 0, 1],
        inliers: 82,
        matchQuality: 'accepted',
        reprojectionErrorPx: 1.8,
        toSourceIndex: 1,
      },
      {
        fromSourceIndex: 1,
        homography3x3: [1, 0.02, 151.6, -0.02, 1, 1.7, 0, 0, 1],
        inliers: 76,
        matchQuality: 'accepted',
        reprojectionErrorPx: 2.1,
        toSourceIndex: 2,
      },
    ],
    ransacSeed: 12345,
    ransacInlierThresholdPx: 5,
    ransacIterations: 2500,
  },
  artifactId: 'artifact_panorama_session_0001',
  boundaryMode: 'auto_crop',
  boundarySettings: {
    crop: {
      height: 3900,
      mode: 'auto',
      width: 9200,
      x: 42,
      y: 18,
    },
    effectiveMode: 'auto_crop',
    requestedMode: 'auto_crop',
    support: 'implemented_current_engine',
  },
  createdAt: '2026-06-13T07:30:00.000Z',
  crop: {
    height: 3900,
    mode: 'auto',
    width: 9200,
    x: 42,
    y: 18,
  },
  excludedSources: [],
  engine: {
    capabilities: {
      adaptiveSeamFeather: true,
      autoCrop: false,
      bundleAdjustment: false,
      cylindricalProjection: false,
      exposureNormalization: false,
      planarHomography: true,
      tiledRender: false,
    },
    engineId: 'rapidraw_homography_seam_v0',
    qualityTier: 'legacy_local_preview',
  },
  exposureNormalization: {
    deferredReason: 'Current panorama runtime records planned exposure normalization but does not apply it yet.',
    mode: 'planned',
    overlapMetrics: {
      channelRatioDeltaBefore: 0.09,
      medianLogLuminanceDeltaBefore: 0.14,
    },
    support: 'schema_only_deferred',
  },
  lensCorrectionPolicy: 'required_before_stitch',
  operationId: 'merge.panorama.create',
  operationVersion: 1,
  outputArtifacts: [
    {
      artifactId: 'artifact_panorama_session_0001_output',
      contentHash: 'sha256:sample-panorama-output',
      dimensions: {
        height: 3900,
        width: 9200,
      },
      kind: 'merge_output',
      storage: 'sidecar_artifact',
    },
  ],
  outputColorSpace: 'linear_rec2020_d65_v1',
  previewArtifacts: [
    {
      artifactId: 'artifact_panorama_session_0001_preview',
      contentHash: 'sha256:sample-panorama-preview',
      dimensions: {
        height: 543,
        width: 1280,
      },
      kind: 'preview',
      storage: 'temp_cache',
    },
  ],
  projection: 'rectilinear',
  projectionSettings: {
    effectiveProjection: 'rectilinear',
    horizontalFovDegrees: 72,
    inputFocalLength35mmEquivalentMm: 28,
    requestedProjection: 'rectilinear',
    support: 'implemented_current_engine',
  },
  provenance: {
    commandId: 'command_panorama_create_sample',
    graphRevision: 'graph_rev_43',
    runtimeStatus: 'schema_only',
  },
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  seamPolicy: {
    featherWidthPx: 100,
    lowDetailFeatherMultiplier: 5,
    mode: 'adaptive_dp_feather_v1',
  },
  sourceImageRefs: [
    {
      imagePath: '/photos/pano/IMG_0001.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 0,
      virtualCopyId: null,
    },
    {
      imagePath: '/photos/pano/IMG_0002.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 1,
      virtualCopyId: null,
    },
    {
      imagePath: '/photos/pano/IMG_0003.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 2,
      virtualCopyId: null,
    },
  ],
  validationMetrics: {
    estimatedPeakMemoryBytes: 2200000000,
    excludedSourceCount: 0,
    overlapCoverageRatio: 0.28,
    outputHeight: 3900,
    outputWidth: 9200,
    reprojectionP95Px: 3.4,
    reprojectionRmsPx: 1.9,
    seamEnergy: 0.18,
    sourceCount: 3,
    stitchedSourceCount: 3,
  },
  warnings: ['exposure_mismatch'],
});

const lowConfidenceLabWarning = {
  blocksAutomation: true,
  code: 'low_acquisition_confidence',
  evidence: 'Lab JPEG source has lossy compression and no scanner profile metadata.',
  frameIds: ['frame_0001'],
  scope: 'session',
  severity: 'warning',
};

export const sampleNegativeAcquisitionProfileV1: NegativeAcquisitionProfileV1 =
  negativeAcquisitionProfileV1Schema.parse({
    acquisitionConfidence: 'low',
    autoColorSuspected: true,
    autoContrastSuspected: true,
    autoExposureSuspected: true,
    bitDepth: 8,
    captureDeviceName: 'Unknown lab scanner',
    captureDeviceType: 'lab_scanner',
    channelClippingScore: 0.12,
    compressionArtifactScore: 0.42,
    compressionKind: 'lossy',
    createdFrom: 'metadata.classifier.v1',
    dustRemovalSuspected: false,
    fileFormat: 'jpeg',
    frameSpacingState: 'single_frame',
    inputMode: 'lab_jpeg',
    inputProfileSource: 'assumed_display_profile',
    irCleaningSuspected: false,
    lightSourceConfidence: 'low',
    lightSourceType: 'lab_unknown',
    pixelBasis: 'lab_rendered_rgb',
    preInversionSuspected: false,
    profileConfidence: 'low',
    profileId: 'acq_lab_jpeg_sample_v1',
    rebateOrBorderState: 'cropped_out',
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    sharpeningSuspected: true,
    unevenIlluminationScore: 0.18,
    visibleBaseState: 'not_visible',
    warnings: [
      lowConfidenceLabWarning,
      {
        blocksAutomation: true,
        code: 'lossy_input',
        evidence: 'JPEG compression was detected from the source container.',
        frameIds: ['frame_0001'],
        scope: 'frame',
        severity: 'warning',
      },
    ],
  });

export const sampleNegativeRollSessionV1: NegativeRollSessionV1 = negativeRollSessionV1Schema.parse({
  acquisitionProfileId: sampleNegativeAcquisitionProfileV1.profileId,
  acquisitionWarnings: [lowConfidenceLabWarning],
  anchorFrameIds: [],
  conversionWarnings: [],
  frameRecords: [
    {
      baseSampleIds: [],
      borderState: 'cropped',
      contentHash: 'sha256:sample-negative-frame-hash',
      conversionCommandIds: [],
      frameId: 'frame_0001',
      frameIndex: 0,
      positiveVariantIds: [],
      qcStatus: 'needs_review',
      sourcePath: '/photos/roll-01/lab-scan-0001.jpg',
      warningCodes: ['lossy_input', 'low_acquisition_confidence'],
    },
  ],
  inputMode: 'lab_jpeg',
  perFrameOverrideIds: [],
  pixelBasis: 'lab_rendered_rgb',
  processFamily: 'c41_color_negative',
  provenanceEntryIds: ['prov_import_lab_scan_0001'],
  qcStatus: 'needs_review',
  rollDefaultCommandIds: [],
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  sessionId: 'negative_roll_session_sample',
  sharedBaseSampleIds: [],
  sourceFileIds: ['source_lab_scan_0001'],
});

export const sampleNegativeLabCommandEnvelopeV1: NegativeLabCommandEnvelopeV1 =
  negativeLabCommandEnvelopeV1Schema.parse({
    actor: {
      id: 'codex-app-server',
      kind: ActorKind.Agent,
      sessionId: 'session_sample',
    },
    approval: {
      approvalClass: ApprovalClass.PreviewOnly,
      reason: 'Negative conversion dry-run returns a preview artifact before mutating the roll session.',
      state: 'not_required',
    },
    commandId: 'command_negative_convert_frames_sample',
    commandType: 'negativeLab.convertFrames',
    correlationId: 'corr_negative_convert_frames_sample',
    dryRun: true,
    expectedGraphRevision: 'graph_rev_negative_7',
    idempotencyKey: 'idem_negative_convert_frames_sample',
    parameters: {
      baseSampleIds: ['base_sample_roll_01'],
      densityModel: 'log_transmittance',
      frameIds: ['frame_0001'],
      inversionMethod: 'neutral_base',
      outputIntent: 'editable_positive',
      preserveDensityArtifacts: true,
      processFamily: 'c41_color_negative',
      sessionId: sampleNegativeRollSessionV1.sessionId,
      targetWorkingSpace: 'linear_prophoto_rgb',
    },
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    target: {
      id: sampleNegativeRollSessionV1.sessionId,
      kind: 'roll',
    },
  });
