import {
  ActorKind,
  ApprovalClass,
  RAW_ENGINE_SCHEMA_VERSION,
  NEGATIVE_LAB_COMMAND_TYPES,
  artifactHandleV1Schema,
  commandEnvelopeV1Schema,
  negativeAcquisitionProfileV1Schema,
  negativeLabAppServerToolManifestV1Schema,
  negativeLabApplyPlanRequestV1Schema,
  negativeLabApplyResultV1Schema,
  negativeLabBuiltInPresetCatalogV1Schema,
  negativeLabCommandEnvelopeV1Schema,
  negativeLabDensityNormalizationProfileV1Schema,
  negativeLabDryRunResultV1Schema,
  negativeLabFrameDetectionResultV1Schema,
  negativeLabPositiveVariantProvenanceV1Schema,
  negativeLabProcessProfileV1Schema,
  negativeLabQcProofArtifactV1Schema,
  negativeRollSessionV1Schema,
  panoramaArtifactV1Schema,
  queryEnvelopeV1Schema,
  rawEngineToolRegistryV1Schema,
  type ArtifactHandleV1,
  type CommandEnvelopeV1,
  type NegativeAcquisitionProfileV1,
  type NegativeLabAppServerToolManifestV1,
  type NegativeLabApplyPlanRequestV1,
  type NegativeLabApplyResultV1,
  type NegativeLabBuiltInPresetCatalogV1,
  type NegativeLabCommandEnvelopeV1,
  type NegativeLabDensityNormalizationProfileV1,
  type NegativeLabDryRunResultV1,
  type NegativeLabFrameDetectionResultV1,
  type NegativeLabPositiveVariantProvenanceV1,
  type NegativeLabProcessProfileV1,
  type NegativeLabQcProofArtifactV1,
  type NegativeRollSessionV1,
  type PanoramaArtifactV1,
  type QueryEnvelopeV1,
  type RawEngineToolRegistryV1,
} from './rawEngineSchemas.js';

export const sampleQueryEnvelopeV1: QueryEnvelopeV1 = queryEnvelopeV1Schema.parse({
  actor: {
    id: 'codex-app-server',
    kind: ActorKind.Agent,
    sessionId: 'session_sample',
  },
  correlationId: 'corr_metadata_sample',
  parameters: {
    includeExif: true,
  },
  queryId: 'query_metadata_sample',
  queryType: 'image.getMetadata',
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  target: {
    imagePath: '/photos/session/IMG_0001.CR3',
    kind: 'image',
  },
});

export const sampleCommandEnvelopeV1: CommandEnvelopeV1 = commandEnvelopeV1Schema.parse({
  actor: {
    id: 'codex-app-server',
    kind: ActorKind.Agent,
    sessionId: 'session_sample',
  },
  approval: {
    approvalClass: ApprovalClass.PreviewOnly,
    reason: 'Tone dry-run does not persist sidecars or exported files.',
    state: 'not_required',
  },
  commandId: 'command_tone_dry_run_sample',
  commandType: 'edit.tone.dryRun',
  correlationId: 'corr_tone_dry_run_sample',
  dryRun: true,
  expectedGraphRevision: 'graph_rev_42',
  parameters: {
    exposureEv: 0.25,
    highlights: -12,
  },
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  target: {
    imagePath: '/photos/session/IMG_0001.CR3',
    kind: 'image',
    virtualCopyId: null,
  },
});

export const sampleArtifactHandleV1: ArtifactHandleV1 = artifactHandleV1Schema.parse({
  artifactId: 'artifact_preview_sample',
  contentHash: 'sha256:sample-preview-hash',
  dimensions: {
    height: 1080,
    width: 1620,
  },
  kind: 'preview',
  storage: 'temp_cache',
});

export const sampleToolRegistryV1: RawEngineToolRegistryV1 = rawEngineToolRegistryV1Schema.parse({
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  tools: [
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'QueryEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ImageMetadataResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'image.get_metadata',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'CommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ToneDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'edit.dry_run_tone',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'NegativeLabCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'NegativeLabDryRunResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'negativelab.preview_conversion',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'NegativeLabApplyPlanRequestV1',
      mutates: true,
      outputSchemaName: 'NegativeLabApplyResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'negativelab.apply_planned_command',
    },
  ],
});

export const samplePanoramaArtifactV1: PanoramaArtifactV1 = panoramaArtifactV1Schema.parse({
  alignment: {
    algorithmId: 'rapidraw_fast9_brief_ransac_v1',
    downscaleMaxDimensionPx: 1600,
    globalHomographyCount: 3,
    minimumInliersForConnection: 15,
    pairwiseMatches: [
      {
        fromSourceIndex: 0,
        homography3x3: [1, 0.01, 148.2, -0.01, 1, 2.4, 0, 0, 1],
        inliers: 82,
        matchQuality: 'accepted',
        reprojectionErrorPx: 1.8,
        toSourceIndex: 1,
      },
      {
        fromSourceIndex: 1,
        homography3x3: [1, 0.02, 151.6, -0.02, 1, 1.7, 0, 0, 1],
        inliers: 76,
        matchQuality: 'accepted',
        reprojectionErrorPx: 2.1,
        toSourceIndex: 2,
      },
    ],
    ransacSeed: 12345,
    ransacInlierThresholdPx: 5,
    ransacIterations: 2500,
  },
  artifactId: 'artifact_panorama_session_0001',
  boundaryMode: 'auto_crop',
  boundarySettings: {
    crop: {
      height: 3900,
      mode: 'auto',
      width: 9200,
      x: 42,
      y: 18,
    },
    effectiveMode: 'auto_crop',
    requestedMode: 'auto_crop',
    support: 'implemented_current_engine',
  },
  createdAt: '2026-06-13T07:30:00.000Z',
  crop: {
    height: 3900,
    mode: 'auto',
    width: 9200,
    x: 42,
    y: 18,
  },
  excludedSources: [],
  engine: {
    capabilities: {
      adaptiveSeamFeather: true,
      autoCrop: false,
      bundleAdjustment: false,
      cylindricalProjection: false,
      exposureNormalization: false,
      planarHomography: true,
      tiledRender: false,
    },
    engineId: 'rapidraw_homography_seam_v0',
    qualityTier: 'legacy_local_preview',
  },
  exposureNormalization: {
    deferredReason: 'Current panorama runtime records planned exposure normalization but does not apply it yet.',
    mode: 'planned',
    overlapMetrics: {
      channelRatioDeltaBefore: 0.09,
      medianLogLuminanceDeltaBefore: 0.14,
    },
    support: 'schema_only_deferred',
  },
  lensCorrectionPolicy: 'required_before_stitch',
  operationId: 'merge.panorama.create',
  operationVersion: 1,
  outputArtifacts: [
    {
      artifactId: 'artifact_panorama_session_0001_output',
      contentHash: 'sha256:sample-panorama-output',
      dimensions: {
        height: 3900,
        width: 9200,
      },
      kind: 'merge_output',
      storage: 'sidecar_artifact',
    },
  ],
  outputColorSpace: 'linear_rec2020_d65_v1',
  previewArtifacts: [
    {
      artifactId: 'artifact_panorama_session_0001_preview',
      contentHash: 'sha256:sample-panorama-preview',
      dimensions: {
        height: 543,
        width: 1280,
      },
      kind: 'preview',
      storage: 'temp_cache',
    },
  ],
  projection: 'rectilinear',
  projectionSettings: {
    effectiveProjection: 'rectilinear',
    horizontalFovDegrees: 72,
    inputFocalLength35mmEquivalentMm: 28,
    requestedProjection: 'rectilinear',
    support: 'implemented_current_engine',
  },
  provenance: {
    commandId: 'command_panorama_create_sample',
    graphRevision: 'graph_rev_43',
    runtimeStatus: 'schema_only',
  },
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  seamPolicy: {
    featherWidthPx: 100,
    lowDetailFeatherMultiplier: 5,
    mode: 'adaptive_dp_feather_v1',
  },
  sourceImageRefs: [
    {
      imagePath: '/photos/pano/IMG_0001.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 0,
      virtualCopyId: null,
    },
    {
      imagePath: '/photos/pano/IMG_0002.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 1,
      virtualCopyId: null,
    },
    {
      imagePath: '/photos/pano/IMG_0003.CR3',
      lensCorrectionState: 'required_before_stitch',
      rawDefaultsApplied: true,
      sourceIndex: 2,
      virtualCopyId: null,
    },
  ],
  validationMetrics: {
    estimatedPeakMemoryBytes: 2200000000,
    excludedSourceCount: 0,
    overlapCoverageRatio: 0.28,
    outputHeight: 3900,
    outputWidth: 9200,
    reprojectionP95Px: 3.4,
    reprojectionRmsPx: 1.9,
    seamEnergy: 0.18,
    sourceCount: 3,
    stitchedSourceCount: 3,
  },
  warnings: ['exposure_mismatch'],
});

const lowConfidenceLabWarning = {
  blocksAutomation: true,
  code: 'low_acquisition_confidence',
  evidence: 'Lab JPEG source has lossy compression and no scanner profile metadata.',
  frameIds: ['frame_0001'],
  scope: 'session',
  severity: 'warning',
};

export const sampleNegativeAcquisitionProfileV1: NegativeAcquisitionProfileV1 =
  negativeAcquisitionProfileV1Schema.parse({
    acquisitionConfidence: 'low',
    autoColorSuspected: true,
    autoContrastSuspected: true,
    autoExposureSuspected: true,
    bitDepth: 8,
    captureDeviceName: 'Unknown lab scanner',
    captureDeviceType: 'lab_scanner',
    channelClippingScore: 0.12,
    compressionArtifactScore: 0.42,
    compressionKind: 'lossy',
    createdFrom: 'metadata.classifier.v1',
    dustRemovalSuspected: false,
    fileFormat: 'jpeg',
    frameSpacingState: 'single_frame',
    inputMode: 'lab_jpeg',
    inputProfileSource: 'assumed_display_profile',
    irCleaningSuspected: false,
    lightSourceConfidence: 'low',
    lightSourceType: 'lab_unknown',
    pixelBasis: 'lab_rendered_rgb',
    preInversionSuspected: false,
    profileConfidence: 'low',
    profileId: 'acq_lab_jpeg_sample_v1',
    rebateOrBorderState: 'cropped_out',
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    sharpeningSuspected: true,
    unevenIlluminationScore: 0.18,
    visibleBaseState: 'not_visible',
    warnings: [
      lowConfidenceLabWarning,
      {
        blocksAutomation: true,
        code: 'lossy_input',
        evidence: 'JPEG compression was detected from the source container.',
        frameIds: ['frame_0001'],
        scope: 'frame',
        severity: 'warning',
      },
    ],
  });

export const sampleNegativeRollSessionV1: NegativeRollSessionV1 = negativeRollSessionV1Schema.parse({
  acquisitionProfileId: sampleNegativeAcquisitionProfileV1.profileId,
  acquisitionWarnings: [lowConfidenceLabWarning],
  anchorFrameIds: [],
  conversionWarnings: [],
  frameRecords: [
    {
      baseSampleIds: [],
      borderState: 'cropped',
      contentHash: 'sha256:sample-negative-frame-hash',
      conversionCommandIds: [],
      frameId: 'frame_0001',
      frameIndex: 0,
      positiveVariantIds: [],
      qcStatus: 'needs_review',
      sourcePath: '/photos/roll-01/lab-scan-0001.jpg',
      warningCodes: ['lossy_input', 'low_acquisition_confidence'],
    },
  ],
  inputMode: 'lab_jpeg',
  perFrameOverrideIds: [],
  pixelBasis: 'lab_rendered_rgb',
  processFamily: 'c41_color_negative',
  provenanceEntryIds: ['prov_import_lab_scan_0001'],
  qcStatus: 'needs_review',
  rollDefaultCommandIds: [],
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  sessionId: 'negative_roll_session_sample',
  sharedBaseSampleIds: [],
  sourceFileIds: ['source_lab_scan_0001'],
});

export const sampleNegativeLabFrameDetectionResultV1: NegativeLabFrameDetectionResultV1 =
  negativeLabFrameDetectionResultV1Schema.parse({
    algorithm: {
      algorithmId: 'frame_split_border_detect_v1',
      algorithmVersion: 1,
      deterministicSeed: 42,
    },
    detectedFrames: [
      {
        borderMetrics: {
          borderConfidence: 'medium',
          borderState: 'partial',
          rebateTextDetected: false,
          sprocketHoleDetected: true,
          visibleBorderPx: {
            bottom: 18,
            left: 24,
            right: 22,
            top: 12,
          },
        },
        contentHash: 'sha256:sample-detected-frame-0001',
        crop: {
          height: 3024,
          rotationDegrees: 0.2,
          width: 4536,
          x: 148,
          y: 96,
        },
        detectionConfidence: 'medium',
        frameId: 'frame_0001',
        frameIndex: 0,
        needsManualReview: true,
        sourceFileId: 'source_lab_scan_0001',
        warningCodes: ['cropped_no_border', 'frame_detection_low_confidence'],
      },
    ],
    detectionRunId: 'frame_detection_roll_01_run_01',
    inputRequest: {
      borderPolicy: 'prefer_visible_border',
      contactSheetHandling: 'suggest_frames',
      detectionSensitivity: 'balanced',
      mode: 'suggest_only',
      preserveOriginalOrientation: true,
    },
    rejectedCandidates: [
      {
        candidateId: 'candidate_overlap_0001',
        crop: {
          height: 2950,
          rotationDegrees: 0.2,
          width: 4450,
          x: 162,
          y: 112,
        },
        reason: 'overlap_duplicate',
        sourceFileId: 'source_lab_scan_0001',
      },
    ],
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    sessionId: sampleNegativeRollSessionV1.sessionId,
    sourceFileIds: ['source_lab_scan_0001'],
    warnings: [
      {
        blocksAutomation: false,
        code: 'frame_detection_low_confidence',
        evidence: 'Only partial border was visible on the top edge.',
        frameIds: ['frame_0001'],
        scope: 'frame',
        severity: 'warning',
      },
    ],
  });

export const sampleNegativeLabDensityNormalizationProfileV1: NegativeLabDensityNormalizationProfileV1 =
  negativeLabDensityNormalizationProfileV1Schema.parse({
    algorithmId: 'density_normalization_v1',
    anchorPolicy: 'roll_anchor_frames',
    channelBalanceWeights: {
      blue: 0.2,
      green: 0.55,
      red: 0.25,
    },
    densityAim: {
      highlightDensity: 0.18,
      midtoneDensity: 0.82,
      shadowDensity: 2.35,
    },
    exposureReferenceDensity: 0.82,
    normalizationProfileId: 'generic_c41_density_norm_v1',
    profileVersion: '2026-06-13',
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    supportedProcessFamilies: ['c41_color_negative'],
  });

export const sampleNegativeLabProcessProfileV1: NegativeLabProcessProfileV1 = negativeLabProcessProfileV1Schema.parse({
  colorMode: 'color_negative_rgb',
  curveModelId: 'process_profile_monotonic_v1',
  densityCurves: [
    {
      channel: 'red',
      interpolation: 'monotone_cubic',
      points: [
        { inputDensity: 0, outputLinear: 0 },
        { inputDensity: 0.4, outputLinear: 0.16 },
        { inputDensity: 1.2, outputLinear: 0.58 },
        { inputDensity: 2.6, outputLinear: 1 },
      ],
    },
    {
      channel: 'green',
      interpolation: 'monotone_cubic',
      points: [
        { inputDensity: 0, outputLinear: 0 },
        { inputDensity: 0.4, outputLinear: 0.18 },
        { inputDensity: 1.2, outputLinear: 0.6 },
        { inputDensity: 2.6, outputLinear: 1 },
      ],
    },
    {
      channel: 'blue',
      interpolation: 'monotone_cubic',
      points: [
        { inputDensity: 0, outputLinear: 0 },
        { inputDensity: 0.4, outputLinear: 0.14 },
        { inputDensity: 1.2, outputLinear: 0.54 },
        { inputDensity: 2.6, outputLinear: 1 },
      ],
    },
  ],
  normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
  processFamily: 'c41_color_negative',
  profileClass: 'generic_process',
  profileId: 'generic_c41_v1',
  profileVersion: '2026-06-13',
  provenance: {
    claimsPolicy: 'generic_starting_point_only',
    fixtureIds: [],
    legalNamingStatus: 'generic_safe_name',
    measurementSource: 'generic_engineered_starting_point',
  },
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  touchedParameters: {
    creativeRendering: [],
    objectiveInversion: ['density_rgb_v1'],
    semiObjectiveNormalization: ['density_normalization_v1'],
  },
  warningCodes: [],
});

export const sampleNegativeLabBuiltInPresetCatalogV1: NegativeLabBuiltInPresetCatalogV1 =
  negativeLabBuiltInPresetCatalogV1Schema.parse({
    catalogId: 'negative_lab.generic.v1',
    catalogVersion: '2026-06-13',
    presets: [
      {
        claimLevel: 'generic_starting_point_only',
        description: 'Balanced C-41 color negative starting point for well-scanned rolls.',
        displayName: 'C-41 Neutral',
        filmClass: 'color_negative',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'neutral',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        presetId: 'negative_lab.generic.c41.neutral.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'c41_color_negative',
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: [sampleNegativeLabProcessProfileV1.profileId],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Linearized scan data is preferred.', 'Visible film border improves base sampling.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'C-41 color negative starting point tuned for gentle skin-tone contrast.',
        displayName: 'C-41 Portrait',
        filmClass: 'color_negative',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'portrait',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        presetId: 'negative_lab.generic.c41.portrait.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'c41_color_negative',
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: [sampleNegativeLabProcessProfileV1.profileId],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Neutral base sample is available.', 'Mixed lighting may need manual balance review.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'C-41 color negative starting point for denser high-speed scans.',
        displayName: 'C-41 High Speed',
        filmClass: 'color_negative',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff', 'lab_jpeg'],
        intent: 'high_speed',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        presetId: 'negative_lab.generic.c41.high_speed.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'c41_color_negative',
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: [sampleNegativeLabProcessProfileV1.profileId],
        },
        requiredWarningCodes: ['lossy_input', 'low_acquisition_confidence'],
        scanAssumptions: ['Lab-rendered files require review.', 'Visible border is preferred for base sampling.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'C-41 color negative starting point with stronger color separation.',
        displayName: 'C-41 Saturated',
        filmClass: 'color_negative',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'saturated',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        presetId: 'negative_lab.generic.c41.saturated.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'c41_color_negative',
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: [sampleNegativeLabProcessProfileV1.profileId],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Clipped channels should be reviewed before conversion.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'Silver black-and-white negative starting point with classic tonal placement.',
        displayName: 'Black and White Classic',
        filmClass: 'black_and_white_silver',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'classic_bw',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: 'generic_bw_silver_density_norm_v1',
        normalizationProfileVersion: '2026-06-13',
        presetId: 'negative_lab.generic.bw.classic.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'black_and_white_silver_negative',
        processProfileId: 'generic_bw_silver_v1',
        processProfileVersion: '2026-06-13',
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: ['generic_bw_silver_v1'],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Luminance conversion is expected.', 'Base fog sample should avoid rebate marks.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'Silver black-and-white negative starting point with smoother midtone separation.',
        displayName: 'Black and White Fine Grain',
        filmClass: 'black_and_white_silver',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'fine_grain_bw',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: 'generic_bw_silver_density_norm_v1',
        normalizationProfileVersion: '2026-06-13',
        presetId: 'negative_lab.generic.bw.fine_grain.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'black_and_white_silver_negative',
        processProfileId: 'generic_bw_silver_v1',
        processProfileVersion: '2026-06-13',
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: ['generic_bw_silver_v1'],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Low sharpening in the scan is preferred.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
      {
        claimLevel: 'generic_starting_point_only',
        description: 'Silver black-and-white negative starting point for ortho-style tonal relationships.',
        displayName: 'Black and White Ortho',
        filmClass: 'black_and_white_silver',
        intendedInputModes: ['camera_raw', 'camera_tiff', 'flatbed_tiff', 'lab_tiff'],
        intent: 'ortho_bw',
        legalNamingStatus: 'generic_safe_name',
        legalReviewStatus: 'not_required_generic',
        normalizationProfileId: 'generic_bw_silver_density_norm_v1',
        normalizationProfileVersion: '2026-06-13',
        presetId: 'negative_lab.generic.bw.ortho.v1',
        presetTier: 'generic_builtin',
        presetVersion: '2026-06-13',
        processFamily: 'black_and_white_silver_negative',
        processProfileId: 'generic_bw_silver_v1',
        processProfileVersion: '2026-06-13',
        provenance: {
          claimsPolicy: 'generic_starting_point_only',
          fixtureIds: [],
          legalNote: 'Generic RawEngine starting point with no brand or stock claim.',
          measurementSource: 'generic_engineered_starting_point',
          sourceProfileIds: ['generic_bw_silver_v1'],
        },
        requiredWarningCodes: [],
        scanAssumptions: ['Color-filtered capture changes should be reviewed separately.'],
        schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
        touchedParameters: {
          creativeRendering: [],
          objectiveInversion: ['density_rgb_v1'],
          semiObjectiveNormalization: ['density_normalization_v1'],
        },
      },
    ],
    processProfileRefs: [
      {
        colorMode: 'color_negative_rgb',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        processFamily: 'c41_color_negative',
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
      },
      {
        colorMode: 'black_and_white_luminance',
        normalizationProfileId: 'generic_bw_silver_density_norm_v1',
        normalizationProfileVersion: '2026-06-13',
        processFamily: 'black_and_white_silver_negative',
        processProfileId: 'generic_bw_silver_v1',
        processProfileVersion: '2026-06-13',
      },
    ],
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  });

export const sampleNegativeLabCommandEnvelopeV1: NegativeLabCommandEnvelopeV1 =
  negativeLabCommandEnvelopeV1Schema.parse({
    actor: {
      id: 'codex-app-server',
      kind: ActorKind.Agent,
      sessionId: 'session_sample',
    },
    approval: {
      approvalClass: ApprovalClass.PreviewOnly,
      reason: 'Negative conversion dry-run returns a preview artifact before mutating the roll session.',
      state: 'not_required',
    },
    commandId: 'command_negative_set_conversion_recipe_sample',
    commandType: 'negativeLab.setConversionRecipe',
    correlationId: 'corr_negative_set_conversion_recipe_sample',
    dryRun: true,
    expectedGraphRevision: 'graph_rev_negative_7',
    idempotencyKey: 'idem_negative_set_conversion_recipe_sample',
    parameters: {
      baseStrategy: {
        baseEstimateId: 'base_estimate_roll_01',
        baseSampleIds: ['base_sample_roll_01'],
        mode: 'existing_base_estimate',
      },
      conversionModel: {
        algorithmId: 'density_rgb_v1',
        algorithmVersion: 1,
        densityMax: 4,
        epsilonPolicyId: 'density_epsilon_v1',
        negativeDensityTolerance: 0.02,
      },
      curveModel: {
        curveFamily: 'process_profile_monotonic_v1',
        normalizationProfileId: sampleNegativeLabDensityNormalizationProfileV1.normalizationProfileId,
        normalizationProfileVersion: sampleNegativeLabDensityNormalizationProfileV1.profileVersion,
        processProfileId: sampleNegativeLabProcessProfileV1.profileId,
        processProfileVersion: sampleNegativeLabProcessProfileV1.profileVersion,
      },
      frameSelection: {
        excludeFrameIds: [],
        frameIds: ['frame_0001'],
        mode: 'selected',
        qcStatuses: [],
        warningCodes: [],
      },
      inputCharacterization: {
        channelBasis: 'scanner_rgb',
        confidence: 'approximate_rendered_rgb',
        pixelBasis: 'linear_scan_rgb',
      },
      neutralization: {
        mode: 'neutral_sample',
        sampleIds: ['base_sample_roll_01'],
      },
      outputIntent: 'editable_positive',
      outputTransformRef: {
        chromaticAdaptation: 'bradford',
        renderingIntent: 'scene_referred',
        transformId: 'rawengine_scene_linear_v1',
      },
      previewRequest: {
        artifactPurposes: ['objective_positive_preview', 'base_sample_overlay', 'warning_report'],
        includePreview: true,
        maxEdgePx: 1600,
      },
      processFamily: 'c41_color_negative',
      sessionId: sampleNegativeRollSessionV1.sessionId,
    },
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    target: {
      id: sampleNegativeRollSessionV1.sessionId,
      kind: 'roll',
    },
  });

const sampleNegativeLabChangeSet = {
  artifactHandles: [sampleArtifactHandleV1],
  createdPositiveVariantIds: ['positive_variant_frame_0001'],
  provenanceEntryIds: ['prov_negative_convert_frames_sample'],
  updatedFrameIds: ['frame_0001'],
  updatedSessionId: sampleNegativeRollSessionV1.sessionId,
  warningCodes: ['lossy_input', 'low_acquisition_confidence'],
};

export const sampleNegativeLabDryRunResultV1: NegativeLabDryRunResultV1 = negativeLabDryRunResultV1Schema.parse({
  changeSet: sampleNegativeLabChangeSet,
  commandId: sampleNegativeLabCommandEnvelopeV1.commandId,
  commandType: sampleNegativeLabCommandEnvelopeV1.commandType,
  correlationId: sampleNegativeLabCommandEnvelopeV1.correlationId,
  dryRunPlanId: 'dry_run_plan_negative_conversion_sample',
  numericMetrics: {
    estimatedBaseClippingScore: 0.04,
    previewDeltaEWarningScore: 0.8,
  },
  previewArtifacts: [sampleArtifactHandleV1],
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  warnings: sampleNegativeRollSessionV1.acquisitionWarnings,
});

export const sampleNegativeLabApplyPlanRequestV1: NegativeLabApplyPlanRequestV1 =
  negativeLabApplyPlanRequestV1Schema.parse({
    acknowledgedWarningCodes: ['lossy_input', 'low_acquisition_confidence'],
    commandId: sampleNegativeLabCommandEnvelopeV1.commandId,
    dryRunPlanId: sampleNegativeLabDryRunResultV1.dryRunPlanId,
    expectedSessionRevision: 'session_rev_negative_7',
    sessionId: sampleNegativeRollSessionV1.sessionId,
  });

export const sampleNegativeLabApplyResultV1: NegativeLabApplyResultV1 = negativeLabApplyResultV1Schema.parse({
  appliedGraphRevision: 'graph_rev_negative_8',
  changeSet: sampleNegativeLabChangeSet,
  commandId: 'command_negative_convert_frames_apply_sample',
  commandType: sampleNegativeLabCommandEnvelopeV1.commandType,
  correlationId: sampleNegativeLabCommandEnvelopeV1.correlationId,
  dryRunCommandId: sampleNegativeLabCommandEnvelopeV1.commandId,
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  sessionId: sampleNegativeRollSessionV1.sessionId,
  warnings: sampleNegativeRollSessionV1.acquisitionWarnings,
});

export const sampleNegativeLabPositiveVariantProvenanceV1: NegativeLabPositiveVariantProvenanceV1 =
  negativeLabPositiveVariantProvenanceV1Schema.parse({
    acknowledgedWarningCodes: sampleNegativeLabApplyPlanRequestV1.acknowledgedWarningCodes,
    acquisitionProfileId: sampleNegativeRollSessionV1.acquisitionProfileId,
    applyCommandId: sampleNegativeLabApplyResultV1.commandId,
    baseSampleIds: ['base_sample_roll_01'],
    conversionCommandId: sampleNegativeLabCommandEnvelopeV1.commandId,
    conversionRecipeId: 'conversion_recipe_negative_roll_01',
    createdAt: '2026-06-13T00:00:00.000Z',
    createdBy: sampleNegativeLabCommandEnvelopeV1.actor,
    dryRunPlanId: sampleNegativeLabApplyPlanRequestV1.dryRunPlanId,
    graphRevision: sampleNegativeLabApplyResultV1.appliedGraphRevision,
    inheritedRollDefaults: true,
    outputIntent: 'editable_positive',
    outputTransformRef: {
      chromaticAdaptation: 'bradford',
      renderingIntent: 'scene_referred',
      transformId: 'rawengine_scene_linear_v1',
    },
    positiveVariantId: 'positive_variant_frame_0001',
    previewArtifactHandles: sampleNegativeLabDryRunResultV1.previewArtifacts,
    processFamily: 'c41_color_negative',
    provenanceEntryIds: sampleNegativeLabApplyResultV1.changeSet.provenanceEntryIds,
    rollSessionId: sampleNegativeRollSessionV1.sessionId,
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    sourceContentHash: 'sha256:sample-negative-frame-hash',
    sourceFileId: 'source_lab_scan_0001',
    sourceFrameId: 'frame_0001',
    variantName: 'Frame 0001 positive',
    variantNameSource: 'generated_generic',
    warningCodes: sampleNegativeLabApplyResultV1.changeSet.warningCodes,
  });

export const sampleNegativeLabQcProofArtifactV1: NegativeLabQcProofArtifactV1 =
  negativeLabQcProofArtifactV1Schema.parse({
    contactSheet: {
      artifact: {
        artifactId: 'artifact_negative_lab_qc_contact_sheet',
        contentHash: 'sha256:sample-negative-lab-qc-proof',
        dimensions: {
          height: 1200,
          width: 1800,
        },
        kind: 'preview',
        storage: 'temp_cache',
      },
      columns: 3,
      rows: 1,
    },
    frameIds: ['frame_0001'],
    generatedAt: '2026-06-13T00:10:00.000Z',
    overlays: [
      {
        frameId: 'frame_0001',
        geometry: {
          coordinateSpace: 'frame_pixels_after_crop',
          height: 3024,
          kind: 'rect',
          width: 4536,
          x: 0,
          y: 0,
        },
        label: 'Frame boundary requires review',
        overlayId: 'overlay_frame_boundary_0001',
        overlayKind: 'frame_boundary',
        severity: 'warning',
        warningCodes: ['cropped_no_border', 'frame_detection_low_confidence'],
      },
      {
        frameId: 'frame_0001',
        geometry: {
          coordinateSpace: 'normalized_frame',
          height: 0.08,
          kind: 'rect',
          width: 0.12,
          x: 0.04,
          y: 0.88,
        },
        label: 'Base sample',
        overlayId: 'overlay_base_sample_0001',
        overlayKind: 'base_sample',
        severity: 'info',
        warningCodes: [],
      },
    ],
    proofId: 'negative_lab_qc_proof_roll_01',
    rollConsistency: {
      anchorFrameIds: ['frame_0001'],
      densityDeltaTolerance: 0.08,
      exposureDeltaToleranceEv: 0.25,
      frameMetrics: [
        {
          densityDelta: 0,
          exposureDeltaEv: 0,
          frameId: 'frame_0001',
          warningCodes: [],
          whiteBalanceDelta: 0,
          withinTolerance: true,
        },
      ],
      metricVersion: 1,
      whiteBalanceDeltaTolerance: 0.08,
    },
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    sessionId: sampleNegativeRollSessionV1.sessionId,
    warnings: sampleNegativeLabFrameDetectionResultV1.warnings,
  });

export const sampleNegativeLabAppServerToolManifestV1: NegativeLabAppServerToolManifestV1 =
  negativeLabAppServerToolManifestV1Schema.parse({
    schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
    serverRuntime: 'openai_app_server',
    tools: [
      {
        allowedCommandTypes: [...NEGATIVE_LAB_COMMAND_TYPES],
        approvalClass: ApprovalClass.PreviewOnly,
        auditEvents: ['negative_lab_dry_run_requested', 'negative_lab_dry_run_completed'],
        description: 'Preview a Negative Lab command and return a dry-run plan with non-mutating artifacts.',
        executionMode: 'dry_run_command',
        inputSchemaName: 'NegativeLabCommandEnvelopeV1',
        localOnly: true,
        mutates: false,
        outputSchemaName: 'NegativeLabDryRunResultV1',
        requiresDryRunPlan: false,
        returnsArtifactHandles: true,
        toolName: 'negativelab.preview_conversion',
      },
      {
        allowedCommandTypes: [...NEGATIVE_LAB_COMMAND_TYPES],
        approvalClass: ApprovalClass.EditApply,
        auditEvents: ['negative_lab_apply_requested', 'negative_lab_apply_completed'],
        description: 'Apply a previously generated Negative Lab dry-run plan after local operator approval.',
        executionMode: 'apply_dry_run_plan',
        inputSchemaName: 'NegativeLabApplyPlanRequestV1',
        localOnly: true,
        mutates: true,
        outputSchemaName: 'NegativeLabApplyResultV1',
        requiresDryRunPlan: true,
        returnsArtifactHandles: true,
        toolName: 'negativelab.apply_planned_command',
      },
    ],
  });
