import {
  ApprovalClass,
  RAW_ENGINE_SCHEMA_VERSION,
  rawEngineToolRegistryV1Schema,
  type RawEngineToolRegistryV1,
} from './rawEngineSchemas.js';

export const rawEngineDefaultToolRegistryV1: RawEngineToolRegistryV1 = rawEngineToolRegistryV1Schema.parse({
  schemaVersion: RAW_ENGINE_SCHEMA_VERSION,
  tools: [
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'QueryEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ImageMetadataResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'image.get_metadata',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'RawEngineLocalAppServerProjectMetadataQueryV1',
      mutates: false,
      outputSchemaName: 'RawEngineLocalAppServerProjectMetadataResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'agent.project_metadata.query',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'RawEngineLocalAppServerSelectedImagesQueryV1',
      mutates: false,
      outputSchemaName: 'RawEngineLocalAppServerSelectedImagesResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'agent.selected_images.query',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'RawEngineLocalAppServerImageMetadataQueryV1',
      mutates: false,
      outputSchemaName: 'RawEngineLocalAppServerImageMetadataResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'agent.image_metadata.query',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'RawEngineLocalAppServerEditorStateQueryV1',
      mutates: false,
      outputSchemaName: 'RawEngineLocalAppServerEditorStateResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'agent.editor_state.query',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'CommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ToneDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'edit.dry_run_tone',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ToneColorCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ToneColorDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'tonecolor.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'ToneColorCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ToneColorMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'apply',
      toolName: 'tonecolor.apply_command',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'EditGraphSnapshotQueryV1',
      mutates: false,
      outputSchemaName: 'EditGraphSnapshotV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'editgraph.snapshot',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'EditGraphCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'EditGraphDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'editgraph.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'EditGraphCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'EditGraphMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'apply',
      toolName: 'editgraph.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'LayerMaskCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'LayerMaskDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'layermask.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'LayerMaskCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'LayerMaskMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'apply',
      toolName: 'layermask.apply_command',
    },
    {
      approvalClass: ApprovalClass.ExternalModel,
      inputSchemaName: 'AiToolCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'AiToolDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'ai.mask.dry_run_subject',
    },
    {
      approvalClass: ApprovalClass.GenerativeEdit,
      inputSchemaName: 'AiToolCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'AiToolApplyResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'ai.mask.apply_subject',
    },
    {
      approvalClass: ApprovalClass.ExternalModel,
      inputSchemaName: 'AiEnhancementCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'AiEnhancementDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'ai.enhancement.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.GenerativeEdit,
      inputSchemaName: 'AiEnhancementCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'AiEnhancementApplyResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'ai.enhancement.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ComputationalMergeDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'computationalmerge.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ComputationalMergeMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'computationalmerge.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ComputationalMergeDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'computationalmerge.panorama.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ComputationalMergeMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'computationalmerge.panorama.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ComputationalMergeDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'computationalmerge.focus_stack.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ComputationalMergeMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'computationalmerge.focus_stack.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ComputationalMergeDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'computationalmerge.super_resolution.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'ComputationalMergeCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ComputationalMergeMutationResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'computationalmerge.super_resolution.apply_command',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'PreviewScopeQueryV1',
      mutates: false,
      outputSchemaName: 'PreviewScopeResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'preview',
      toolName: 'preview.read_scopes',
    },
    {
      approvalClass: ApprovalClass.SafeRead,
      inputSchemaName: 'ProjectLibrarySnapshotQueryV1',
      mutates: false,
      outputSchemaName: 'ProjectLibrarySnapshotV1',
      requiresDryRun: false,
      returnsArtifactHandles: false,
      toolKind: 'read',
      toolName: 'project.library_snapshot',
    },
    {
      approvalClass: ApprovalClass.FileMutation,
      inputSchemaName: 'ProjectLibraryCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ProjectLibraryMutationResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: false,
      toolKind: 'apply',
      toolName: 'project.library_mutate',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'ExportCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'ExportDryRunResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'export.dry_run_command',
    },
    {
      approvalClass: ApprovalClass.FileMutation,
      inputSchemaName: 'ExportCommandEnvelopeV1',
      mutates: true,
      outputSchemaName: 'ExportApplyResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'export',
      toolName: 'export.write_files',
    },
    {
      approvalClass: ApprovalClass.PreviewOnly,
      inputSchemaName: 'NegativeLabCommandEnvelopeV1',
      mutates: false,
      outputSchemaName: 'NegativeLabDryRunResultV1',
      requiresDryRun: false,
      returnsArtifactHandles: true,
      toolKind: 'dry_run',
      toolName: 'negativelab.preview_conversion',
    },
    {
      approvalClass: ApprovalClass.EditApply,
      inputSchemaName: 'NegativeLabApplyPlanRequestV1',
      mutates: true,
      outputSchemaName: 'NegativeLabApplyResultV1',
      requiresDryRun: true,
      returnsArtifactHandles: true,
      toolKind: 'apply',
      toolName: 'negativelab.apply_planned_command',
    },
  ],
});
