name: CI Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-14'
            target: aarch64-apple-darwin
            asset-prefix: '02'
          - platform: 'macos-15-intel'
            target: x86_64-apple-darwin
            asset-prefix: '02'
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
    secrets: inherit
    permissions:
      contents: write
