name: CI Build

on:
  pull_request:

jobs:
  build:
    name: macOS app build baseline
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-14'
            target: aarch64-apple-darwin
            asset-prefix: '02'
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
